namespace MC.IMS.TESTS.MockData.Reference;

public static class Approvers
{
    public static IEnumerable<API.Models.Result.Reference.Approvers> ApproversList() =>
    [
        new()
        {
            MCOrAgentId = "AGT1006",
            FirstName = "Carlos",
            MiddleName = "Emmanuel",
            LastName = "Mendoza",
            Suffix = null,
            FullName = "Carlos E. Mendoza",
            EmailAddress = "carlos.mendoza@gmail.com",
            ContactNumber = "+639176782345",
            DateOfBirth = new DateTime(1987, 03, 19),
            Address1 = "45 Sta. Rosa Road",
            Address2 = "Nuvali Heights",
            AddressTownId = 3814,
            Address = "45 Sta. Rosa Road, Nuvali Heights, Cabatacan East, Lasam, Cagayan, Region II, Philippines",
            IsActive = true,
            Id = 1,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            MCOrAgentId = "AGT1007",
            FirstName = "Jasmine",
            MiddleName = null,
            LastName = "Flores",
            Suffix = null,
            FullName = "Jasmine Flores",
            EmailAddress = "jasmine.flores@masterconnoisseurs.com",
            ContactNumber = "+639181234987",
            DateOfBirth = new DateTime(1996, 11, 08),
            Address1 = "Blk 6 Lot 20",
            Address2 = "Palm Grove Subd.",
            AddressTownId = 3962,
            Address = "Blk 6 Lot 20, Palm Grove Subd., Villa, Santa Teresita, Cagayan, Region II, Philippines",
            IsActive = true,
            Id = 2,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            MCOrAgentId = "AGT1008",
            FirstName = "Nathan",
            MiddleName = "Oliver",
            LastName = "Gutierrez",
            Suffix = "III",
            FullName = "Nathan O. Gutierrez III",
            EmailAddress = "nathan.gutierrez@masterconnoisseurs.com",
            ContactNumber = "+639192224466",
            DateOfBirth = new DateTime(1989, 06, 25),
            Address1 = "Purok 7",
            Address2 = null,
            AddressTownId = 4082,
            Address = "Purok 7, Capatan, Tuguegarao City (Capital), Cagayan, Region II, Philippines",
            IsActive = true,
            Id = 3,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            MCOrAgentId = "AGT1009",
            FirstName = "Patricia",
            MiddleName = "Ysobel",
            LastName = "Del Rosario",
            Suffix = null,
            FullName = "Patricia Y. Del Rosario",
            EmailAddress = "patricia.delrosario@masterconnoisseurs.com",
            ContactNumber = "+639175551234",
            DateOfBirth = new DateTime(1993, 01, 17),
            Address1 = "Zone 3",
            Address2 = "Sitio Kabilang Bakod",
            AddressTownId = 10258,
            Address = "Zone 3, Sitio Kabilang Bakod, Congbalay-Legaspi, Kawit, Cavite, Region IV-A, Philippines",
            IsActive = true,
            Id = 4,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            MCOrAgentId = "AGT1010",
            FirstName = "Jericho",
            MiddleName = "Benedict",
            LastName = "Salvador",
            Suffix = "Sr.",
            FullName = "Jericho B. Salvador Sr.",
            EmailAddress = "jericho.salvador@masterconnoisseurs.com",
            ContactNumber = "+639184447788",
            DateOfBirth = new DateTime(1980, 08, 03),
            Address1 = "#12 Sunset Blvd",
            Address2 = "Tierra Verde",
            AddressTownId = 10345,
            Address = "#12 Sunset Blvd, Tierra Verde, Ibayo Silangan, Naic, Cavite, Region IV-A, Philippines",
            IsActive = true,
            Id = 5,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
    ];
}