namespace MC.IMS.TESTS.MockData.Reference;

public static class Benefits
{
    public static IEnumerable<API.Models.Result.Reference.Benefits> BenefitsList() =>
    [
        new()
        {
            Id = 1,
            Name = "Accidental Death Benefit",
            Description = "Accidental Death Benefit",
            Code = "ADB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 2,
            Name = "Accidental Dismemberment and/or Disablement Benefit",
            Description = "Accidental Dismemberment and/or Disablement Benefit",
            Code = "ADDB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 3,
            Name = "Murder and Unprovoked Assault Benefit",
            Description = "Murder and Unprovoked Assault Benefit",
            Code = "MUAB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 4,
            Name = "Fire Cash Assistance",
            Description = "Fire Cash Assistance",
            Code = "FCA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 5,
            Name = "Death Benefit (Accidental or Sickness)",
            Description = "Death Benefit (Accidental or Sickness)",
            Code = "DB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 6,
            Name = "Accident or Sickness Emergency Cash Assistance",
            Description = "Accident or Sickness Emergency Cash Assistance",
            Code = "ECA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 7,
            Name = "TeleHealth",
            Description = "TeleHealth",
            Code = "TH",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 8,
            Name = "Life Benefit",
            Description = "Life Benefit",
            Code = "LIFE",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 9,
            Name = "Dengue Cash Assistance",
            Description = "Dengue Cash Assistance",
            Code = "DCA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 10,
            Name = "ER Maximum Benefit Limit",
            Description = "ER Maximum Benefit Limit",
            Code = "ERMBL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 11,
            Name = "Livelihood Cash Assistance due to Accidental Death",
            Description = "Livelihood Cash Assistance due to Accidental Death",
            Code = "LHCA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 12,
            Name = "Leptos Cash Assistance",
            Description = "Leptos Cash Assistance",
            Code = "LCA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 13,
            Name = "Medicine Reimbursement",
            Description = "Medicine Reimbursement",
            Code = "MDCR",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 14,
            Name = "Hospital Income Benefit",
            Description = "Hospital Income Benefit",
            Code = "HIB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 15,
            Name = "Burial Benefit (Accident)",
            Description = "Burial Benefit (Accident)",
            Code = "BBA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 16,
            Name = "Death Benefit (Dengue)",
            Description = "Death Benefit (Dengue)",
            Code = "DBD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 17,
            Name = "Death Benefit (Chikungunya)",
            Description = "Death Benefit (Chikungunya)",
            Code = "DBCH",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 18,
            Name = "Death Benefit (Covid-19)",
            Description = "Death Benefit (Covid-19)",
            Code = "DBCV",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 19,
            Name = "Hospital Income Benefit (Covid-19)",
            Description = "Hospital Income Benefit (Covid-19)",
            Code = "HIBCV",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 20,
            Name = "Personal Liability",
            Description = "Personal Liability",
            Code = "PL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 21,
            Name = "Motorcycling Coverage",
            Description = "Motorcycling Coverage",
            Code = "MC",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 22,
            Name = "Third Party Liability",
            Description = "Third Party Liability",
            Code = "TPL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 23,
            Name = "Medical Reimbursement (Pet Benefit)",
            Description = "Medical Reimbursement (Pet Benefit)",
            Code = "MRPB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 24,
            Name = "Cash Assistance (Food Poisoning)",
            Description = "Food Poisoning Cash Assistance",
            Code = "FPSN",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 25,
            Name = "Total Permanent Disability",
            Description = "Total Permanent Disability",
            Code = "TPD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 26,
            Name = "Accidental Total Permanent Disability",
            Description = "Accidental Total Permanent Disability",
            Code = "ATPD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 27,
            Name = "Elligible days for Hospital Income Benefit",
            Description = "Elligible days for Hospital Income Benefit",
            Code = "HIBDays",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 28,
            Name = "Hospital Income Benefit (Accident)",
            Description = "Hospital Income Benefit (Accident)",
            Code = "HIBA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 29,
            Name = "Elligible days for Hospital Income Benefit (Accident)",
            Description = "Elligible days for Hospital Income Benefit (Accident)",
            Code = "HIBDayAcc",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 30,
            Name = "Medical Reimbursement (Accident)",
            Description = "Medical Reimbursement (Accident)",
            Code = "MRA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 31,
            Name = "Elligible days for Hospital Income Benefit (Covid-19)",
            Description = "Elligible days for Hospital Income Benefit (Covid-19)",
            Code = "DHIBCV",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 32,
            Name = "Accidental Death (Spouse/Parent)",
            Description = "Accidental Death (Spouse/Parent)",
            Code = "SAD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 33,
            Name = "Accidental Dismemberment and/or Disablement Benefit (Spouse/Parent)",
            Description = "Accidental Dismemberment and/or Disablement Benefit (Spouse/Parent)",
            Code = "SADD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 34,
            Name = "Murder and Unprovoked Assault Benefit (Spouse/Parent)",
            Description = "Murder and Unprovoked Assault Benefit (Spouse/Parent)",
            Code = "SMUA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 35,
            Name = "Death Benefit (Spouse/Parent)",
            Description = "Death Benefit (Spouse/Parent)",
            Code = "SDB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 36,
            Name = "Medical Reimbursement (Accident) (Spouse/Parent)",
            Description = "Medical Reimbursement (Accident) (Spouse/Parent)",
            Code = "SAMR",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 37,
            Name = "Accidental Death (Children/Siblings)",
            Description = "Accidental Death (Children/Siblings)",
            Code = "CAD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 38,
            Name = "Accidental Dismemberment and/or Disablement Benefit (Children/Siblings)",
            Description = "Accidental Dismemberment and/or Disablement Benefit (Children/Siblings)",
            Code = "CADD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 39,
            Name = "Murder and Unprovoked Assault Benefit (Children/Siblings)",
            Description = "Murder and Unprovoked Assault Benefit (Children/Siblings)",
            Code = "CMUA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 40,
            Name = "Death Benefit (Children/Siblings)",
            Description = "Death Benefit (Children/Siblings)",
            Code = "CDB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 41,
            Name = "Medical Reimbursement (Accident) (Children/Siblings)",
            Description = "Medical Reimbursement (Accident) (Children/Siblings)",
            Code = "CAMR",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 42,
            Name = "Critical Illness Benefit",
            Description = "Critical Illness Benefit",
            Code = "CIB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 43,
            Name = "Cracked Screen Protection Benefit",
            Description = "Cracked Screen Protection Benefit",
            Code = "CSP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 44,
            Name = "Accidental Dismemberment and/or Disablement Benefit",
            Description = "Accidental Dismemberment and/or Disablement Benefit (Short Scale Benefit)",
            Code = "ADDBS",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 45,
            Name = "Accidental Dismemberment and/or Disablement Benefit (Spouse/Parent)",
            Description = "Accidental Dismemberment and/or Disablement Benefit (Spouse/Parent) (Short Scale Benefit)",
            Code = "SADDBS",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 46,
            Name = "Accidental Dismemberment and/or Disablement Benefit (Children/Sibling)",
            Description =
                "Accidental Dismemberment and/or Disablement Benefit (Children/Sibling) (Short Scale Benefit)",
            Code = "CADDBS",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 47,
            Name = "Terrorism Total Permanent Disability",
            Description = "Terrorism Total Permanent Disability",
            Code = "TTPD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 48,
            Name = "Pet Euthanized Death Cash Assistance",
            Description = "Pet Euthanized Death Cash Assistance",
            Code = "PEDCA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 49,
            Name = "Food Poisoning Cash Assistance",
            Description = "Food Poisoning Cash Assistance",
            Code = "FPCA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 50,
            Name = "Mental Health Benefits (Online & Teleconsultation)",
            Description = "Mental Health Benefits (Online & Teleconsultation)",
            Code = "MHTH",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 51,
            Name = "Maximum Benefit Limit",
            Description = "Maximum Benefit Limit",
            Code = "MBL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 52,
            Name = "Surety (Downpayment) Bond",
            Description = "Surety (Downpayment) Bond",
            Code = "SBND",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 53,
            Name = "Bidder’s Bond",
            Description = "Bidder’s bond",
            Code = "BBND",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 54,
            Name = "Performance Bond",
            Description = "Performance Bond",
            Code = "PBND",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 55,
            Name = "Warranty Bond",
            Description = "Warranty Bond",
            Code = "WBND",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 56,
            Name = "Fidelity Bond",
            Description = "Fidelity Bond",
            Code = "FBND",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 57,
            Name = "Heir's Bond",
            Description = "Heir's Bond",
            Code = "HBND",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 58,
            Name = "Material Damage",
            Description = "Material Damage",
            Code = "MADG",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 59,
            Name = "Third Party Liability Combined BI PD",
            Description = "Third Party Liability Combined BI PD",
            Code = "CombinedSingleLimitBIPD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 60,
            Name = "Fire and/or Lightning",
            Description = "Fire and/or Lightning Only (Property)",
            Code = "FL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 61,
            Name = "Earthquake",
            Description = "Earthquake (Property)",
            Code = "EQ",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 62,
            Name = "Typhoon",
            Description = "Typhoon (Property)",
            Code = "TYP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 63,
            Name = "Flood",
            Description = "Flood (Property)",
            Code = "FLP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 64,
            Name = "Extended Coverage",
            Description = "Extended Coverage (Property)",
            Code = "ECP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 65,
            Name = "Riot, Strike & Malicious Damage (RSMD)",
            Description = "Riot, Strike & Malicious Damage (RSMD) (Property)",
            Code = "RSMD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 66,
            Name = "Comprehensive General Liability",
            Description = "Comprehensive General Liability (Property)",
            Code = "CGL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 67,
            Name = "Bursting of Water Tanks, Apparatuses & Pipes (BOWTAP)",
            Description = "Bursting of Water Tanks, Apparatuses & Pipes (BOWTAP) (Property)",
            Code = "BOWTAP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 68,
            Name = "Medical Reimbursement (Accident/Illness)",
            Description = "Medical Reimbursement (Accident/Illness)",
            Code = "MRCP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 69,
            Name = "Medical Evacuation and Repatriation",
            Description = "Medical Evacuation and Repatriation",
            Code = "MER",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 70,
            Name = "Emergency Dental Care",
            Description = "Emergency Dental Care",
            Code = "EMDC",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 71,
            Name = "Return of a family member traveling with the Insured",
            Description = "Return of a family member traveling with the Insured",
            Code = "RFMT",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 72,
            Name = "Escort of Dependent Child",
            Description = "Escort of Dependent Child",
            Code = "EDC",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 73,
            Name = "Compassionate Visit",
            Description = "Compassionate Visit",
            Code = "CV",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 74,
            Name = "Delayed Departure/Flight",
            Description = "Delayed Departure/Flight",
            Code = "DDF",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 75,
            Name = "Missed Connecting Flights",
            Description = "Missed Connecting Flights",
            Code = "MCF",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 76,
            Name = "Trip Cancellation",
            Description = "Trip Cancellation",
            Code = "TCA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 77,
            Name = "Trip Curtailment",
            Description = "Trip Curtailment",
            Code = "TCU",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 78,
            Name = "Baggage Delay",
            Description = "Baggage Delay",
            Code = "BD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 79,
            Name = "Loss of Baggage",
            Description = "Loss of Baggage",
            Code = "LB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 80,
            Name = "Hospital Income Benefit (Accident/Illness)",
            Description = "Hospital Income Benefit (Accident/Illness)",
            Code = "HIBI",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 81,
            Name = "Robbery",
            Description = "Robbery",
            Code = "RB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 82,
            Name = "Fraud/Dishonesty",
            Description = "Fraud/Dishonesty",
            Code = "FOD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 83,
            Name = "Robbery / Hold-up",
            Description = "Robbery / Hold-up",
            Code = "ROH",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 84,
            Name = "Own Damage and Theft",
            Description = "Own Damage and Theft",
            Code = "ODT",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 85,
            Name = "Variable Third Party - Bodily Injury",
            Description = "Variable Third Party - Bodily Injury",
            Code = "VTPBI",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 86,
            Name = "Variable Third Party - Property Damage",
            Description = "Variable Third Party - Property Damage",
            Code = "VTPPD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 87,
            Name = "Unnamed Passenger Personal Accident",
            Description = "Unnamed Passenger Personal Accident",
            Code = "UPPA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 88,
            Name = "Additional Unnamed Passenger Personal Accident",
            Description = "Additional Unnamed Passenger Personal Accident",
            Code = "AUPPA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 89,
            Name = "Acts of Nature",
            Description = "Acts of Nature",
            Code = "AON",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 90,
            Name = "Face Amount",
            Description = "Face Amount",
            Code = "FaceAmount",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 91,
            Name = "Accidental Ambulance Benefit",
            Description = "Accidental Ambulance Benefit",
            Code = "AAB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 92,
            Name = "Medical Expenses",
            Description =
                "Covers costs for medical emergencies, including doctor visits, hospital stays, medication, and even emergency dental treatment that may arise due to illness or accidents during your trip.",
            Code = "MEDXP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 93,
            Name = "Trip Cancellation and Interruption",
            Description =
                "If your trip is canceled or cut short due to unforeseen circumstances like illness, injury, death of a family member, natural disasters, or even certain travel supplier bankruptcies.",
            Code = "TRPCI",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 94,
            Name = "Lost, Stolen, or Delayed Baggage",
            Description = "Can compensate you for the loss, theft, or damage of your luggage and personal belongings.",
            Code = "LSTBG",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 95,
            Name = "Travel Delays and Missed Connections",
            Description =
                "Cover additional expenses such as accommodation, meals, and transportation. It can also provide coverage if you miss a connecting flight due to a delay.",
            Code = "TRVDY",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 96,
            Name = "Personal Liability",
            Description =
                "Protect you if you accidentally cause damage to someone's property or injure another person during your travels. It can help cover legal costs and compensation you may be required to pay.",
            Code = "PERLB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 97,
            Name = "Repatriation of Remains",
            Description = null,
            Code = "REPRM",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 98,
            Name = "Trip Cancellation",
            Description = null,
            Code = "TRPCN",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 99,
            Name = "Trip Interruption",
            Description = null,
            Code = "TRPIN",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 100,
            Name = "Baggage Delay",
            Description = null,
            Code = "BAGDY",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 101,
            Name = "Accidental Death and Dismemberment",
            Description = null,
            Code = "ACCTH",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 102,
            Name = "Identity Theft Assistance",
            Description = null,
            Code = "IDTHF",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 103,
            Name = "Hull (Physical Damage)",
            Description = null,
            Code = "HULLD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 104,
            Name = "Passenger Liability",
            Description = null,
            Code = "PASLB",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 105,
            Name = "Cargo Liability",
            Description = null,
            Code = "CARGL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 106,
            Name = "Hangarkeeper's Liability",
            Description = null,
            Code = "HANGR",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 107,
            Name = "Ground Risks Hull Coverage",
            Description = null,
            Code = "GRNHC",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 108,
            Name = "In-Flight Hull Coverage",
            Description = null,
            Code = "INFLC",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 109,
            Name = "Personal Accident (Crew/Passengers)",
            Description = null,
            Code = "PERAC",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 110,
            Name = "Spares Coverage",
            Description = null,
            Code = "SPARS",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 111,
            Name = "Non-Owned Aircraft Liability",
            Description = null,
            Code = "NONAL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 112,
            Name = "Airport Liability",
            Description = null,
            Code = "AIRPT",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 113,
            Name = "Products Liability",
            Description = null,
            Code = "PRODL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 114,
            Name = "Crew Legal Liability",
            Description = null,
            Code = "CREWL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 115,
            Name = "Search and Rescue Expenses",
            Description = null,
            Code = "SRCHR",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 116,
            Name = "Data Breach Costs",
            Description = "First-Party Coverage",
            Code = "DBC",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 117,
            Name = "Business Interruption",
            Description = "First-Party Coverage",
            Code = "BI",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 118,
            Name = "Data Recovery and System Restoration",
            Description = "First-Party Coverage",
            Code = "DRS",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 119,
            Name = "Cyber Extortion",
            Description = "First-Party Coverage",
            Code = "CE",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 120,
            Name = "Damage to Digital Assets",
            Description = "First-Party Coverage",
            Code = "DDA",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 121,
            Name = "Fraud and Funds Transfer Loss",
            Description = "First-Party Coverage",
            Code = "FTL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 122,
            Name = "Privacy Liability",
            Description = "Third-Party Coverage",
            Code = "PRL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 123,
            Name = "Network Security Liability",
            Description = "Third-Party Coverage",
            Code = "NSL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 124,
            Name = "Regulatory Defense and Penalties",
            Description = "Third-Party Coverage",
            Code = "RDP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 125,
            Name = "Media Liability",
            Description = "Third-Party Coverage",
            Code = "ML",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 126,
            Name = "Errors and Omissions (E&O) Coverage",
            Description = "Third-Party Coverage",
            Code = "EOE",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 127,
            Name = "Pre-Incident Support",
            Description = "Additional Coverages",
            Code = "PIS",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 128,
            Name = "Incident Response Services",
            Description = "Additional Coverages",
            Code = "IRS",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        },
        new()
        {
            Id = 129,
            Name = "Reputation Management",
            Description = "Additional Coverages",
            Code = "RM",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 6, 2, 0, 0, 0),
        }
    ];
}