namespace MC.IMS.TESTS.MockData.Reference;

public static class Clients
{
    public static IEnumerable<API.Models.Result.Reference.Clients> ClientsList() =>
    [
        new()
        {
            Id = 6,
            InsuranceCustomerNo = "INSC123456",
            FirstName = "Juan",
            MiddleName = "M",
            LastName = "Dela Cruz",
            Suffix = null,
            FullName = "Juan M. Dela Cruz",
            EmailAddress = "juan.delacruz@gmail.com",
            ContactNumber = "+639171234567",
            DateOfBirth = new DateTime(1985, 04, 15),
            IsMale = true,
            ValidIdPresented = 1,
            ValidIdPresentedNumber = "DL123456789",
            ValidIdExpiration = new DateTime(2027, 04, 14),
            Address1 = "123 Mabini St.",
            Address2 = null,
            AddressTownId = 11209,
            Address = "123 Mabini St., Macasipac, Santa Maria, Laguna, Region IV-A, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 7,
            InsuranceCustomerNo = "INSC123457",
            FirstName = "Maria",
            MiddleName = "L",
            LastName = "Santos",
            Suffix = "Jr.",
            FullName = "Maria L. Santos Jr.",
            EmailAddress = "maria.santos@gmail.com",
            ContactNumber = "+639181234568",
            DateOfBirth = new DateTime(1990, 09, 30),
            IsMale = false,
            ValidIdPresented = 2,
            ValidIdPresentedNumber = "P1234567",
            ValidIdExpiration = new DateTime(2030, 09, 29),
            Address1 = "456 Mabini Ave.",
            Address2 = null,
            AddressTownId = 11844,
            Address = "456 Mabini Ave., Vegaflor, Lopez, Quezon, Region IV-A, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 8,
            InsuranceCustomerNo = "INSC123458",
            FirstName = "Carlos",
            MiddleName = null,
            LastName = "Reyes",
            Suffix = null,
            FullName = "Carlos Reyes",
            EmailAddress = "carlos.reyes@gmail.com",
            ContactNumber = "+639191234569",
            DateOfBirth = new DateTime(1978, 12, 05),
            IsMale = true,
            ValidIdPresented = 3,
            ValidIdPresentedNumber = "SSS987654321",
            ValidIdExpiration = new DateTime(2028, 12, 04),
            Address1 = "789 Mabini Blvd.",
            Address2 = null,
            AddressTownId = 12750,
            Address = "789 Mabini Blvd., Sawi, Boac (Capital), Marinduque, Region IV-B, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 9,
            InsuranceCustomerNo = "INSC123459",
            FirstName = "Ana",
            MiddleName = "P",
            LastName = "Garcia",
            Suffix = null,
            FullName = "Ana P. Garcia",
            EmailAddress = "ana.garcia@gmail.com",
            ContactNumber = "+639201234570",
            DateOfBirth = new DateTime(1982, 07, 20),
            IsMale = false,
            ValidIdPresented = 4,
            ValidIdPresentedNumber = "UMID11223344",
            ValidIdExpiration = new DateTime(2026, 07, 19),
            Address1 = "101 Mabini Rd.",
            Address2 = null,
            AddressTownId = 13559,
            Address = "101 Mabini Rd., Pasig, Balabac, Palawan, Region IV-B, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 10,
            InsuranceCustomerNo = "INSC123460",
            FirstName = "Jose",
            MiddleName = "R",
            LastName = "Torres",
            Suffix = null,
            FullName = "Jose R. Torres",
            EmailAddress = "jose.torres@gmail.com",
            ContactNumber = "+639211234571",
            DateOfBirth = new DateTime(1975, 11, 11),
            IsMale = true,
            ValidIdPresented = 5,
            ValidIdPresentedNumber = "VOTER7654321",
            ValidIdExpiration = new DateTime(2025, 11, 10),
            Address1 = "202 Mabini St.",
            Address2 = null,
            AddressTownId = 14108,
            Address = "202 Mabini St., Calunacon, San Andres, Romblon, Region IV-B, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 11,
            InsuranceCustomerNo = "INSC123461",
            FirstName = "Luz",
            MiddleName = "D",
            LastName = "Velasco",
            Suffix = null,
            FullName = "Luz D. Velasco",
            EmailAddress = "luz.velasco@gmail.com",
            ContactNumber = "+639221234572",
            DateOfBirth = new DateTime(1988, 02, 18),
            IsMale = false,
            ValidIdPresented = 6,
            ValidIdPresentedNumber = "PH123456789",
            ValidIdExpiration = new DateTime(2029, 02, 17),
            Address1 = "303 Mabini St.",
            Address2 = null,
            AddressTownId = 14502,
            Address = "303 Mabini St., Tambo, Libon, Albay, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 12,
            InsuranceCustomerNo = "INSC123462",
            FirstName = "Ramon",
            MiddleName = null,
            LastName = "Mendoza",
            Suffix = null,
            FullName = "Ramon Mendoza",
            EmailAddress = "ramon.mendoza@gmail.com",
            ContactNumber = "+639231234573",
            DateOfBirth = new DateTime(1972, 10, 03),
            IsMale = true,
            ValidIdPresented = 3,
            ValidIdPresentedNumber = "SSS123987456",
            ValidIdExpiration = new DateTime(2027, 10, 02),
            Address1 = "404 Mabini Ave.",
            Address2 = null,
            AddressTownId = 14624,
            Address = "404 Mabini Ave., Bagumbayan, Oas, Albay, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 13,
            InsuranceCustomerNo = "INSC123463",
            FirstName = "Gloria",
            MiddleName = "S",
            LastName = "Lopez",
            Suffix = null,
            FullName = "Gloria S. Lopez",
            EmailAddress = "gloria.lopez@gmail.com",
            ContactNumber = "+639241234574",
            DateOfBirth = new DateTime(1980, 06, 12),
            IsMale = false,
            ValidIdPresented = 2,
            ValidIdPresentedNumber = "P987654321",
            ValidIdExpiration = new DateTime(2031, 06, 11),
            Address1 = "505 Mabini Rd.",
            Address2 = null,
            AddressTownId = 15838,
            Address = "505 Mabini Rd., San Vicente Ogbon, Nabua, Camarines Sur, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 14,
            InsuranceCustomerNo = "INSC123464",
            FirstName = "Pedro",
            MiddleName = "M",
            LastName = "Cruz",
            Suffix = null,
            FullName = "Pedro M. Cruz",
            EmailAddress = "pedro.cruz@gmail.com",
            ContactNumber = "+639251234575",
            DateOfBirth = new DateTime(1979, 01, 25),
            IsMale = true,
            ValidIdPresented = 5,
            ValidIdPresentedNumber = "VOTER654321",
            ValidIdExpiration = new DateTime(2026, 01, 24),
            Address1 = "606 Mabini St.",
            Address2 = null,
            AddressTownId = 16453,
            Address = "606 Mabini St., Burgos, Viga, Catanduanes, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 15,
            InsuranceCustomerNo = "INSC123465",
            FirstName = "Elena",
            MiddleName = null,
            LastName = "Gomez",
            Suffix = null,
            FullName = "Elena Gomez",
            EmailAddress = "elena.gomez@gmail.com",
            ContactNumber = "+639261234576",
            DateOfBirth = new DateTime(1987, 03, 17),
            IsMale = false,
            ValidIdPresented = 4,
            ValidIdPresentedNumber = "UMID998877",
            ValidIdExpiration = new DateTime(2028, 03, 16),
            Address1 = "707 Mabini Ave.",
            Address2 = null,
            AddressTownId = 16542,
            Address = "707 Mabini Ave., Amotag, Aroroy, Masbate, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 16,
            InsuranceCustomerNo = "INSC123466",
            FirstName = "Juan",
            MiddleName = "P",
            LastName = "Reyes",
            Suffix = null,
            FullName = "Juan P. Reyes",
            EmailAddress = "juan.reyes@gmail.com",
            ContactNumber = "+639271234577",
            DateOfBirth = new DateTime(1983, 07, 21),
            IsMale = true,
            ValidIdPresented = 1,
            ValidIdPresentedNumber = "DL987654321",
            ValidIdExpiration = new DateTime(2029, 07, 20),
            Address1 = "808 Mabini St.",
            Address2 = null,
            AddressTownId = 16739,
            Address = "808 Mabini St., Peñafrancia, Claveria, Masbate, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 17,
            InsuranceCustomerNo = "INSC123467",
            FirstName = "Maria",
            MiddleName = null,
            LastName = "Del Rosario",
            Suffix = null,
            FullName = "Maria Del Rosario",
            EmailAddress = "maria.delrosario@gmail.com",
            ContactNumber = "+639281234578",
            DateOfBirth = new DateTime(1990, 12, 05),
            IsMale = false,
            ValidIdPresented = 2,
            ValidIdPresentedNumber = "P123456789",
            ValidIdExpiration = new DateTime(2030, 12, 04),
            Address1 = "909 Mabini Ave.",
            Address2 = null,
            AddressTownId = 16958,
            Address = "909 Mabini Ave., Dangpanan, Placer, Masbate, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 19,
            InsuranceCustomerNo = "INSC123469",
            FirstName = "Ana",
            MiddleName = "M",
            LastName = "Torres",
            Suffix = null,
            FullName = "Ana M. Torres",
            EmailAddress = "ana.torres@gmail.com",
            ContactNumber = "+639301234580",
            DateOfBirth = new DateTime(1985, 09, 29),
            IsMale = false,
            ValidIdPresented = 4,
            ValidIdPresentedNumber = "UMID654321987",
            ValidIdExpiration = new DateTime(2028, 09, 28),
            Address1 = "1111 Mabini St.",
            Address2 = null,
            AddressTownId = 17763,
            Address = "1111 Mabini St., Linabuan Norte, Kalibo (Capital), Aklan, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 20,
            InsuranceCustomerNo = "INSC123470",
            FirstName = "Jose",
            MiddleName = null,
            LastName = "Garcia",
            Suffix = null,
            FullName = "Jose Garcia",
            EmailAddress = "jose.garcia@gmail.com",
            ContactNumber = "+639311234581",
            DateOfBirth = new DateTime(1978, 05, 14),
            IsMale = true,
            ValidIdPresented = 5,
            ValidIdPresentedNumber = "VOTER123654",
            ValidIdExpiration = new DateTime(2026, 05, 13),
            Address1 = "1212 Mabini Ave.",
            Address2 = null,
            AddressTownId = 18624,
            Address = "1212 Mabini Ave., Jambad, Dumarao, Capiz, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 21,
            InsuranceCustomerNo = "INSC123471",
            FirstName = "Lucia",
            MiddleName = "F",
            LastName = "Velasco",
            Suffix = null,
            FullName = "Lucia F. Velasco",
            EmailAddress = "lucia.velasco@gmail.com",
            ContactNumber = "+639321234582",
            DateOfBirth = new DateTime(1992, 03, 08),
            IsMale = false,
            ValidIdPresented = 6,
            ValidIdPresentedNumber = "PH123456789",
            ValidIdExpiration = new DateTime(2031, 03, 07),
            Address1 = "1234 Rizal St.",
            Address2 = null,
            AddressTownId = 19573,
            Address = "1234 Rizal St., Ermita, Dumangas, Iloilo, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 22,
            InsuranceCustomerNo = "INSC123472",
            FirstName = "Ramon",
            MiddleName = "S",
            LastName = "Lopez",
            Suffix = null,
            FullName = "Ramon S. Lopez",
            EmailAddress = "ramon.lopez@gmail.com",
            ContactNumber = "+639331234583",
            DateOfBirth = new DateTime(1988, 10, 25),
            IsMale = true,
            ValidIdPresented = 1,
            ValidIdPresentedNumber = "DL654987321",
            ValidIdExpiration = new DateTime(2029, 10, 24),
            Address1 = "4321 Mabini Blvd.",
            Address2 = null,
            AddressTownId = 19844,
            Address = "4321 Mabini Blvd., San Nicolas, Iloilo City (Capital), Iloilo, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 23,
            InsuranceCustomerNo = "INSC123473",
            FirstName = "Ella",
            MiddleName = null,
            LastName = "Gonzales",
            Suffix = null,
            FullName = "Ella Gonzales",
            EmailAddress = "ella.gonzales@gmail.com",
            ContactNumber = "+639341234584",
            DateOfBirth = new DateTime(1995, 06, 19),
            IsMale = false,
            ValidIdPresented = 2,
            ValidIdPresentedNumber = "P987654321",
            ValidIdExpiration = new DateTime(2030, 06, 18),
            Address1 = "5678 Mabini St.",
            Address2 = null,
            AddressTownId = 21303,
            Address = "5678 Mabini St., La Granja, La Carlota City, Negros Occidental, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 24,
            InsuranceCustomerNo = "INSC123474",
            FirstName = "Marco",
            MiddleName = "L",
            LastName = "De Guzman",
            Suffix = null,
            FullName = "Marco L. De Guzman",
            EmailAddress = "marco.deguzman@gmail.com",
            ContactNumber = "+639351234585",
            DateOfBirth = new DateTime(1982, 04, 12),
            IsMale = true,
            ValidIdPresented = 3,
            ValidIdPresentedNumber = "SSS321654987",
            ValidIdExpiration = new DateTime(2027, 04, 11),
            Address1 = "7890 Mabini Rd.",
            Address2 = null,
            AddressTownId = 21378,
            Address = "7890 Mabini Rd., Buenavista Rizal, Pontevedra, Negros Occidental, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 25,
            InsuranceCustomerNo = "INSC123475",
            FirstName = "Isabel",
            MiddleName = "T",
            LastName = "Morales",
            Suffix = null,
            FullName = "Isabel T. Morales",
            EmailAddress = "isabel.morales@gmail.com",
            ContactNumber = "+639361234586",
            DateOfBirth = new DateTime(1991, 11, 03),
            IsMale = false,
            ValidIdPresented = 4,
            ValidIdPresentedNumber = "UMID789123456",
            ValidIdExpiration = new DateTime(2028, 11, 02),
            Address1 = "2345 Mabini Ave.",
            Address2 = null,
            AddressTownId = 21854,
            Address = "2345 Mabini Ave., Nueva Montana, Buenavista, Bohol, Region VII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 26,
            InsuranceCustomerNo = "INSC123476",
            FirstName = "Pedro",
            MiddleName = null,
            LastName = "Martinez",
            Suffix = null,
            FullName = "Pedro Martinez",
            EmailAddress = "pedro.martinez@gmail.com",
            ContactNumber = "+639371234587",
            DateOfBirth = new DateTime(1979, 08, 17),
            IsMale = true,
            ValidIdPresented = 5,
            ValidIdPresentedNumber = "VOTER987654",
            ValidIdExpiration = new DateTime(2026, 08, 16),
            Address1 = "3456 Mabini St.",
            Address2 = null,
            AddressTownId = 22952,
            Address = "3456 Mabini St., Matun-og, Balamban, Cebu, Region VII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 27,
            InsuranceCustomerNo = "INSC123477",
            FirstName = "Carla",
            MiddleName = "M",
            LastName = "Reyes",
            Suffix = null,
            FullName = "Carla M. Reyes",
            EmailAddress = "carla.reyes@gmail.com",
            ContactNumber = "+639381234588",
            DateOfBirth = new DateTime(1993, 02, 14),
            IsMale = false,
            ValidIdPresented = 1,
            ValidIdPresentedNumber = "DL789654321",
            ValidIdExpiration = new DateTime(2030, 02, 13),
            Address1 = "5678 Luna St.",
            Address2 = null,
            AddressTownId = 23301,
            Address = "5678 Luna St., Casay, Dalaguete, Cebu, Region VII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 28,
            InsuranceCustomerNo = "INSC123478",
            FirstName = "Diego",
            MiddleName = null,
            LastName = "Salazar",
            Suffix = null,
            FullName = "Diego Salazar",
            EmailAddress = "diego.salazar@gmail.com",
            ContactNumber = "+639391234589",
            DateOfBirth = new DateTime(1987, 07, 22),
            IsMale = true,
            ValidIdPresented = 2,
            ValidIdPresentedNumber = "P123789456",
            ValidIdExpiration = new DateTime(2028, 07, 21),
            Address1 = "4321 Mabini Blvd.",
            Address2 = null,
            AddressTownId = 24081,
            Address = "4321 Mabini Blvd., Tangculogan, Bais City, Negros Oriental, Region VII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 29,
            InsuranceCustomerNo = "INSC123479",
            FirstName = "Francesca",
            MiddleName = "L",
            LastName = "Dela Cruz",
            Suffix = null,
            FullName = "Francesca L. Dela Cruz",
            EmailAddress = "francesca.delacruz@gmail.com",
            ContactNumber = "+639401234590",
            DateOfBirth = new DateTime(1990, 05, 30),
            IsMale = false,
            ValidIdPresented = 3,
            ValidIdPresentedNumber = "SSS654321987",
            ValidIdExpiration = new DateTime(2029, 05, 29),
            Address1 = "1234 Mabini St.",
            Address2 = null,
            AddressTownId = 25013,
            Address = "1234 Mabini St., Barangay Poblacion 8, Lawaan, Eastern Samar, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 30,
            InsuranceCustomerNo = "INSC123480",
            FirstName = "Hector",
            MiddleName = null,
            LastName = "Gomez",
            Suffix = "Jr.",
            FullName = "Hector Gomez Jr.",
            EmailAddress = "hector.gomez@gmail.com",
            ContactNumber = "+639411234591",
            DateOfBirth = new DateTime(1985, 12, 01),
            IsMale = true,
            ValidIdPresented = 4,
            ValidIdPresentedNumber = "UMID321987654",
            ValidIdExpiration = new DateTime(2027, 11, 30),
            Address1 = "9876 Mabini Rd.",
            Address2 = null,
            AddressTownId = 25239,
            Address = "9876 Mabini Rd., Tan-awan, San Policarpo, Eastern Samar, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
    ];
}