namespace MC.IMS.TESTS.MockData.Reference;

public static class Deductibles
{
    public static IEnumerable<API.Models.Result.Reference.Deductibles> DeductiblesList() =>
    [
        new()
        {
            Id = 1,
            Name = "Material Damage - Other Causes",
            Description = "Material Damage - Other Causes",
            Code = "MDOC",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 2,
            Name = "Material Damage - Acts of Nature",
            Description = "Material Damage - Acts of Nature",
            Code = "MDAON",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 3,
            Name = "Third Party Liability - Property Damage Only",
            Description = "Third Party Liability - Property Damage Only",
            Code = "TPLBIPD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 4,
            Name = "Combined Single Limit BIPD",
            Description = "Combined Single Limit BIPD",
            Code = "CSLBIPD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 5,
            Name = "Bodily Injury",
            Description = "Bodily Injury",
            Code = "BODINJ",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 6,
            Name = "Property Damage",
            Description = "Property Damage",
            Code = "PROPD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 7,
            Name = "Food and Drink Liability",
            Description = "Food and Drink Liability",
            Code = "FDL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 8,
            Name = "Premises Medical Payment",
            Description = "Premises Medical Payment",
            Code = "PMP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 9,
            Name = "Tenant's Legal Liability",
            Description = "Tenant's Legal Liability",
            Code = "TLL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 10,
            Name = "Inkeepers Liability",
            Description = "Inkeepers Liability",
            Code = "INKL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 11,
            Name = "Contractual Independent Contractors Liability",
            Description = "Contractual Independent Contractors Liability",
            Code = "CICL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 12,
            Name = "Personal Injury",
            Description = "Personal Injury",
            Code = "PINJ",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 13,
            Name = "Fire and/or Lightning",
            Description = "Fire and/or Lightning",
            Code = "FL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 14,
            Name = "Earthquake",
            Description = "Earthquake",
            Code = "EQ",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 15,
            Name = "Typhoon",
            Description = "Typhoon",
            Code = "TYP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 16,
            Name = "Flood",
            Description = "Flood",
            Code = "FLP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 17,
            Name = "Extended Coverage",
            Description = "Extended Coverage",
            Code = "ECP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 18,
            Name = "Riot, Strike & Malicious Damage (RSMD)",
            Description = "Riot, Strike & Malicious Damage (RSMD)",
            Code = "RSMD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 19,
            Name = "Comprehensive General Liability",
            Description = "Comprehensive General Liability",
            Code = "CGL",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 20,
            Name = "Bursting of Water Tanks, Apparatuses & Pipes (BOWTAP)",
            Description = "Bursting of Water Tanks, Apparatuses & Pipes (BOWTAP)",
            Code = "BOWTAP",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 21,
            Name = "Fraud/Dishonesty",
            Description = "Fraud/Dishonesty",
            Code = "FOD",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 22,
            Name = "Robbery / Hold-up",
            Description = "Robbery / Hold-up",
            Code = "ROH",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
    ];
}