namespace MC.IMS.TESTS.MockData.Reference;

public static class Partners
{
    public static IEnumerable<API.Models.Result.Reference.Partners> PartnersList() =>
    [
        new()
        {
            Id = 1,
            Name = "Sunrise Lending Corp.",
            Description = "Microfinance lender specializing in small business loans.",
            Code = "SLC01",
            ContactPerson = "Anna M. Cruz",
            EmailAddress = "contact@sunriselendingcorp.com",
            ContactNumber = "+639171234567",
            Address1 = "123 Business St.",
            Address2 = null,
            AddressTownId = 26397,
            Address = "123 Business St., Barangay 25 (Pob.), Ormoc City, Leyte, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 2,
            Name = "Pioneer Insurance Co.",
            Description = "Provides affordable microinsurance products to underserved communities.",
            Code = "PIC02",
            ContactPerson = "Carlos R. Mendoza",
            EmailAddress = "info@pioneerinsuranceco.com",
            ContactNumber = "+639181234568",
            Address1 = "456 Insurance Ave.",
            Address2 = null,
            AddressTownId = 28171,
            Address = "456 Insurance Ave., Cabunga-an, Santa Rita, Samar, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 3,
            Name = "Metro Credit Union",
            Description = "Credit union offering loans and savings programs.",
            Code = "MCU03",
            ContactPerson = "Elena V. Garcia",
            EmailAddress = "support@metrocreditunion.com",
            ContactNumber = "+639191234569",
            Address1 = "789 Savings Rd.",
            Address2 = null,
            AddressTownId = 28710,
            Address = "789 Savings Rd., San Jose, Malitbog, Southern Leyte, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 4,
            Name = "Greenfield MFIs",
            Description = "Microfinance institution supporting rural entrepreneurs.",
            Code = "GFM04",
            ContactPerson = "Ramon T. Santos",
            EmailAddress = "contact@greenfieldmfis.com",
            ContactNumber = "+639201234570",
            Address1 = "234 Rural Rd.",
            Address2 = null,
            AddressTownId = 28847,
            Address = "234 Rural Rd., Looc, San Ricardo, Southern Leyte, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 5,
            Name = "Hope Foundation",
            Description = "Non-profit organization providing community support and microloans.",
            Code = "HF05",
            ContactPerson = "Maricel D. Velasco",
            EmailAddress = "info@hopefoundation.org",
            ContactNumber = "+639211234571",
            Address1 = "567 Community Ln.",
            Address2 = null,
            AddressTownId = 28961,
            Address = "567 Community Ln., Canila, Biliran, Biliran, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 6,
            Name = "Bright Future Microfinance",
            Description = "Focused on youth entrepreneurship and financial literacy.",
            Code = "BFM06",
            ContactPerson = "Jorge L. Navarro",
            EmailAddress = "contact@brightfuturemicrofinance.com",
            ContactNumber = "+639221234572",
            Address1 = "101 Innovation Blvd.",
            Address2 = null,
            AddressTownId = 28983,
            Address = "101 Innovation Blvd., Binohangan, Caibiran, Biliran, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 7,
            Name = "Solidarity Finance Group",
            Description = "Provides group lending and community savings plans.",
            Code = "SFG07",
            ContactPerson = "Liza M. De Leon",
            EmailAddress = "info@solidarityfinancegroup.com",
            ContactNumber = "+639231234573",
            Address1 = "202 Unity St.",
            Address2 = null,
            AddressTownId = 30177,
            Address =
                "202 Unity St., San Pedro (Pob.), Pagadian City (Capital), Zamboanga del Sur, Region IX, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 8,
            Name = "Unity Microcredit Bank",
            Description = "Bank specializing in microloans for small enterprises.",
            Code = "UMB08",
            ContactPerson = "Miguel R. Santos",
            EmailAddress = "support@unitymicrocreditbank.com",
            ContactNumber = "+639241234574",
            Address1 = "303 Enterprise Rd.",
            Address2 = null,
            AddressTownId = 30298,
            Address = "303 Enterprise Rd., New Village (Pob.), Tambulig, Zamboanga del Sur, Region IX, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 9,
            Name = "Harmony Microinsurance",
            Description = "Offers affordable insurance plans tailored for micro-entrepreneurs.",
            Code = "HMI09",
            ContactPerson = "Sophia P. Reyes",
            EmailAddress = "contact@harmonymicroinsurance.com",
            ContactNumber = "+639251234575",
            Address1 = "404 Protection St.",
            Address2 = null,
            AddressTownId = 31659,
            Address = "404 Protection St., Mamagum, Sultan Naga Dimaporo, Lanao del Norte, Region X, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 10,
            Name = "CareLink Foundation",
            Description = "Non-profit supporting healthcare microloans and education.",
            Code = "CLF10",
            ContactPerson = "Isabel V. Cruz",
            EmailAddress = "info@carelinkfoundation.org",
            ContactNumber = "+639261234576",
            Address1 = "505 Health Ave.",
            Address2 = null,
            AddressTownId = 32311,
            Address = "505 Health Ave., Mohon, Panaon, Misamis Occidental, Region X, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 11,
            Name = "Prosperity Finance Corp",
            Description = "Offers microloans focused on rural entrepreneurs.",
            Code = "PFC11",
            ContactPerson = "Daniel A. Morales",
            EmailAddress = "contact@prosperityfinancecorp.com",
            ContactNumber = "+639271234577",
            Address1 = "606 Progress St.",
            Address2 = null,
            AddressTownId = 32811,
            Address = "606 Progress St., Salicapawan, Kinoguitan, Misamis Oriental, Region X, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 12,
            Name = "Empower Microfinance",
            Description = "Focused on empowering women entrepreneurs through loans and training.",
            Code = "EMF12",
            ContactPerson = "Clara L. Bautista",
            EmailAddress = "info@empowermicrofinance.com",
            ContactNumber = "+639281234578",
            Address1 = "707 Hope Blvd.",
            Address2 = null,
            AddressTownId = 33025,
            Address = "707 Hope Blvd., Guadalupe, Carmen, Davao del Norte, Region XI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 13,
            Name = "Pioneer Microcredit",
            Description = "Supports startups and new micro-businesses with flexible loans.",
            Code = "PMC13",
            ContactPerson = "Ramon C. Diaz",
            EmailAddress = "support@pioneermicrocredit.com",
            ContactNumber = "+639291234579",
            Address1 = "808 New Venture Rd.",
            Address2 = null,
            AddressTownId = 33219,
            Address = "808 New Venture Rd., Pinamuno, San Isidro, Davao del Norte, Region XI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 14,
            Name = "Hope Credit Alliance",
            Description = "Alliance offering credit lines and insurance for micro-entrepreneurs.",
            Code = "HCA14",
            ContactPerson = "Maria S. Velasco",
            EmailAddress = "contact@hopecreditalliance.com",
            ContactNumber = "+639301234580",
            Address1 = "909 Unity Plaza",
            Address2 = null,
            AddressTownId = 33764,
            Address = "909 Unity Plaza, San Ignacio, Manay, Davao Oriental, Region XI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 15,
            Name = "Unity Trust Microfinance",
            Description = "Trust-based microfinance institution supporting local communities.",
            Code = "UTM15",
            ContactPerson = "Carlos D. Navarro",
            EmailAddress = "info@unitytrustmicrofinance.com",
            ContactNumber = "+639311234581",
            Address1 = "1001 Trust St.",
            Address2 = null,
            AddressTownId = 34370,
            Address = "1001 Trust St., Kabulacan, Matalam, Cotabato, Region XII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 16,
            Name = "Crestview Microfinance",
            Description = "Microfinance provider focusing on agricultural communities.",
            Code = "CMF16",
            ContactPerson = "Elena R. Santos",
            EmailAddress = "contact@crestviewmicrofinance.com",
            ContactNumber = "+639321234582",
            Address1 = "1202 Harvest Lane",
            Address2 = null,
            AddressTownId = 34843,
            Address = "1202 Harvest Lane, Lampitak, Tampakan, South Cotabato, Region XII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 17,
            Name = "Summit Lending Group",
            Description = "Providing flexible loans for small business growth.",
            Code = "SLG17",
            ContactPerson = "Victor M. Reyes",
            EmailAddress = "info@summitlendinggroup.com",
            ContactNumber = "+639331234583",
            Address1 = "1303 Mountain View",
            Address2 = null,
            AddressTownId = 35205,
            Address = "1303 Mountain View, Glan Padidu, Glan, Sarangani, Region XII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 18,
            Name = "Harbor Microcredit",
            Description = "Supports fisherfolk and coastal community entrepreneurs.",
            Code = "HMC18",
            ContactPerson = "Lucia F. dela Cruz",
            EmailAddress = "support@harbormicrocredit.com",
            ContactNumber = "+639341234584",
            Address1 = "1404 Bayview St.",
            Address2 = null,
            AddressTownId = 35372,
            Address = "1404 Bayview St., Barangay 15, Manila City (Capital), Metro Manila, NCR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 19,
            Name = "Greenfield Microfinance",
            Description = "Environmentally sustainable microfinance services.",
            Code = "GMF19",
            ContactPerson = "Felipe G. Navarro",
            EmailAddress = "contact@greenfieldmicrofinance.com",
            ContactNumber = "+639351234585",
            Address1 = "1505 Greenfield Ave.",
            Address2 = null,
            AddressTownId = 36602,
            Address = "1505 Greenfield Ave., Barangay 112, Caloocan City, Metro Manila, NCR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 20,
            Name = "Silverline Credit Union",
            Description = "Credit union supporting artisans and craftsmen.",
            Code = "SCU20",
            ContactPerson = "Anna L. Cruz",
            EmailAddress = "info@silverlinecreditunion.com",
            ContactNumber = "+639361234586",
            Address1 = "1606 Artisan Rd.",
            Address2 = null,
            AddressTownId = 36872,
            Address = "1606 Artisan Rd., Barangay 44, Pasay City, Metro Manila, NCR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
    ];
}