namespace MC.IMS.TESTS.MockData.Reference;

public static class PromoManagers
{
    public static IEnumerable<API.Models.Result.Reference.PromoManagers> PromoManagersList() =>
    [
        new()
        {
            Id = 1,
            AgentsId = 1,
            MCOrAgentId = "AGT031",
            FirstName = "Carlos",
            MiddleName = "R",
            LastName = "Reyes",
            Suffix = null,
            FullName = "Carlos R. Reyes",
            EmailAddress = "carlos.reyes@masterconnoisseurs.com",
            ContactNumber = "+639151234567",
            DateOfBirth = new DateTime(1987, 03, 15),
            Address1 = "654 Mango St.",
            Address2 = "Blk 7 Lot 2",
            AddressTownId = 37150,
            Address = "654 Mango St., Blk 7 Lot 2, Lub-lubba, Dolores, Abra, CAR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 2,
            AgentsId = 1,
            MCOrAgentId = "AGT032",
            FirstName = "Jessa",
            MiddleName = null,
            LastName = "Torres",
            Suffix = "Jr.",
            FullName = "Jessa Torres Jr.",
            EmailAddress = "jessa.torres@masterconnoisseurs.com",
            ContactNumber = "+639178765432",
            DateOfBirth = new DateTime(1990, 11, 09),
            Address1 = "789 Pine Rd.",
            Address2 = "Lot 14",
            AddressTownId = 37464,
            Address = "789 Pine Rd., Lot 14, Teodora Alonzo, Baguio City, Benguet, CAR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 3,
            AgentsId = 1,
            MCOrAgentId = "AGT033",
            FirstName = "Mark",
            MiddleName = "L",
            LastName = "Valdez",
            Suffix = null,
            FullName = "Mark L. Valdez",
            EmailAddress = "mark.valdez@masterconnoisseurs.com",
            ContactNumber = "+639189012345",
            DateOfBirth = new DateTime(1982, 06, 22),
            Address1 = "321 Elm St.",
            Address2 = null,
            AddressTownId = 38049,
            Address = "321 Elm St., Buringal, Paracelis, Mountain Province, CAR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 4,
            AgentsId = 2,
            MCOrAgentId = "AGT034",
            FirstName = "Leah",
            MiddleName = "M",
            LastName = "Garcia",
            Suffix = null,
            FullName = "Leah M. Garcia",
            EmailAddress = "leah.garcia@masterconnoisseurs.com",
            ContactNumber = "+639173456789",
            DateOfBirth = new DateTime(1994, 02, 10),
            Address1 = "432 Birch St.",
            Address2 = "Apt 101",
            AddressTownId = 38703,
            Address = "432 Birch St., Apt 101, Pangadapun, Ganassi, Lanao del Sur, ARMM, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 5,
            AgentsId = 2,
            MCOrAgentId = "AGT035",
            FirstName = "David",
            MiddleName = null,
            LastName = "Luna",
            Suffix = "III",
            FullName = "David Luna III",
            EmailAddress = "david.luna@masterconnoisseurs.com",
            ContactNumber = "+639177654321",
            DateOfBirth = new DateTime(1980, 08, 25),
            Address1 = "987 Spruce Rd.",
            Address2 = null,
            AddressTownId = 39078,
            Address = "987 Spruce Rd., Diampaca, Pagayawan, Lanao del Sur, ARMM, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 6,
            AgentsId = 2,
            MCOrAgentId = "AGT036",
            FirstName = "Maria",
            MiddleName = "C",
            LastName = "Delgado",
            Suffix = null,
            FullName = "Maria C. Delgado",
            EmailAddress = "maria.delgado@masterconnoisseurs.com",
            ContactNumber = "+639170123456",
            DateOfBirth = new DateTime(1992, 12, 01),
            Address1 = "213 Cedar Ln.",
            Address2 = "Unit 3",
            AddressTownId = 39464,
            Address = "213 Cedar Ln., Unit 3, Bangon Proper, Buadiposo-Buntong, Lanao del Sur, ARMM, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 7,
            AgentsId = 3,
            MCOrAgentId = "AGT037",
            FirstName = "Joseph",
            MiddleName = "T",
            LastName = "Salazar",
            Suffix = null,
            FullName = "Joseph T. Salazar",
            EmailAddress = "joseph.salazar@masterconnoisseurs.com",
            ContactNumber = "+639182345678",
            DateOfBirth = new DateTime(1988, 05, 05),
            Address1 = "345 Willow Dr.",
            Address2 = null,
            AddressTownId = 39769,
            Address = "345 Willow Dr., Manion, Parang, Maguindanao, ARMM, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 8,
            AgentsId = 3,
            MCOrAgentId = "AGT038",
            FirstName = "Angela",
            MiddleName = null,
            LastName = "Castillo",
            Suffix = null,
            FullName = "Angela Castillo",
            EmailAddress = "angela.castillo@masterconnoisseurs.com",
            ContactNumber = "+639179876543",
            DateOfBirth = new DateTime(1995, 09, 30),
            Address1 = "876 Maple St.",
            Address2 = null,
            AddressTownId = 40245,
            Address = "876 Maple St., Tayungan, Old Panamao, Sulu, ARMM, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 9,
            AgentsId = 3,
            MCOrAgentId = "AGT039",
            FirstName = "Samuel",
            MiddleName = "V",
            LastName = "Flores",
            Suffix = null,
            FullName = "Samuel V. Flores",
            EmailAddress = "samuel.flores@masterconnoisseurs.com",
            ContactNumber = "+639171234987",
            DateOfBirth = new DateTime(1983, 04, 14),
            Address1 = "654 Oak Ln.",
            Address2 = "Suite 4B",
            AddressTownId = 41083,
            Address = "654 Oak Ln., Suite 4B, Piglawigan, Esperanza, Agusan del Sur, Region XIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 10,
            AgentsId = 4,
            MCOrAgentId = "AGT040",
            FirstName = "Patricia",
            MiddleName = null,
            LastName = "Morales",
            Suffix = null,
            FullName = "Patricia Morales",
            EmailAddress = "patricia.morales@masterconnoisseurs.com",
            ContactNumber = "+639174567890",
            DateOfBirth = new DateTime(1991, 07, 19),
            Address1 = "109 Chestnut Rd.",
            Address2 = null,
            AddressTownId = 41457,
            Address = "109 Chestnut Rd., Cansayong, Malimono, Surigao del Norte, Region XIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 11,
            AgentsId = 4,
            MCOrAgentId = "AGT041",
            FirstName = "Erwin",
            MiddleName = "D",
            LastName = "Navarro",
            Suffix = null,
            FullName = "Erwin D. Navarro",
            EmailAddress = "erwin.navarro@masterconnoisseurs.com",
            ContactNumber = "+639178909876",
            DateOfBirth = new DateTime(1986, 01, 27),
            Address1 = "231 Aspen Dr.",
            Address2 = null,
            AddressTownId = 41680,
            Address = "231 Aspen Dr., San Jose, Bislig City, Surigao del Sur, Region XIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 12,
            AgentsId = 4,
            MCOrAgentId = "AGT042",
            FirstName = "Cynthia",
            MiddleName = "L",
            LastName = "Salvador",
            Suffix = "Sr.",
            FullName = "Cynthia L. Salvador Sr.",
            EmailAddress = "cynthia.salvador@masterconnoisseurs.com",
            ContactNumber = "+639179012345",
            DateOfBirth = new DateTime(1993, 10, 12),
            Address1 = "567 Fir St.",
            Address2 = "Apt 5A",
            AddressTownId = 1126,
            Address = "567 Fir St., Apt 5A, Bulbulala, Santiago, Ilocos Sur, Region I, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 13,
            AgentsId = 5,
            MCOrAgentId = "AGT043",
            FirstName = "Brian",
            MiddleName = "F",
            LastName = "Dela Cruz",
            Suffix = null,
            FullName = "Brian F. Dela Cruz",
            EmailAddress = "brian.delacruz@masterconnoisseurs.com",
            ContactNumber = "+639171098765",
            DateOfBirth = new DateTime(1989, 11, 03),
            Address1 = "890 Redwood Ave.",
            Address2 = null,
            AddressTownId = 1304,
            Address = "890 Redwood Ave., Cabaroan Laud, Vigan City (Capital), Ilocos Sur, Region I, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 14,
            AgentsId = 5,
            MCOrAgentId = "AGT044",
            FirstName = "Monica",
            MiddleName = null,
            LastName = "Villar",
            Suffix = null,
            FullName = "Monica Villar",
            EmailAddress = "monica.villar@masterconnoisseurs.com",
            ContactNumber = "+639172345678",
            DateOfBirth = new DateTime(1996, 06, 07),
            Address1 = "432 Cypress St.",
            Address2 = null,
            AddressTownId = 3081,
            Address = "432 Cypress St., Macaycayawan, Sual, Pangasinan, Region I, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 15,
            AgentsId = 5,
            MCOrAgentId = "AGT045",
            FirstName = "Rafael",
            MiddleName = "S",
            LastName = "Mendoza",
            Suffix = null,
            FullName = "Rafael S. Mendoza",
            EmailAddress = "rafael.mendoza@masterconnoisseurs.com",
            ContactNumber = "+639176543210",
            DateOfBirth = new DateTime(1984, 03, 29),
            Address1 = "210 Sequoia Blvd.",
            Address2 = "Suite 10",
            AddressTownId = 3625,
            Address = "210 Sequoia Blvd., Suite 10, Cadcadir West, Claveria, Cagayan, Region II, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
    ];
}