namespace MC.IMS.TESTS.MockData.Reference;

public static class PromoOfficers
{
    public static IEnumerable<API.Models.Result.Reference.PromoOfficers> PromoOfficersList() =>
    [
        new()
        {
            Id = 1,
            AgentsId = 1,
            MCOrAgentId = "AGT1016",
            FirstName = "Evelyn",
            MiddleName = null,
            LastName = "Santos",
            Suffix = null,
            FullName = "Evelyn Santos",
            EmailAddress = "evelyn.santos@masterconnoisseurs.com",
            ContactNumber = "+639171234001",
            DateOfBirth = new DateTime(1988, 05, 10),
            Address1 = "123 Liberty St.",
            Address2 = null,
            AddressTownId = 3681,
            Address = "123 Liberty St., Guising, Gattaran, Cagayan, Region II, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 2,
            AgentsId = 1,
            MCOrAgentId = "AGT1017",
            FirstName = "Marco",
            MiddleName = "D.",
            LastName = "Lopez",
            Suffix = null,
            FullName = "Marco D. Lopez",
            EmailAddress = "marco.lopez@masterconnoisseurs.com",
            ContactNumber = "+639178899002",
            DateOfBirth = new DateTime(1992, 11, 20),
            Address1 = "456 Pine St.",
            Address2 = null,
            AddressTownId = 3814,
            Address = "456 Pine St., Cabatacan East, Lasam, Cagayan, Region II, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 3,
            AgentsId = 1,
            MCOrAgentId = "AGT1018",
            FirstName = "Diana",
            MiddleName = null,
            LastName = "Morales",
            Suffix = "Jr.",
            FullName = "Diana Morales Jr.",
            EmailAddress = "diana.morales@masterconnoisseurs.com",
            ContactNumber = "+639172255009",
            DateOfBirth = new DateTime(1985, 01, 03),
            Address1 = "789 Oak St.",
            Address2 = null,
            AddressTownId = 3962,
            Address = "789 Oak St., Villa, Santa Teresita, Cagayan, Region II, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 4,
            AgentsId = 2,
            MCOrAgentId = "AGT1019",
            FirstName = "Ricardo",
            MiddleName = "L.",
            LastName = "Garcia",
            Suffix = null,
            FullName = "Ricardo L. Garcia",
            EmailAddress = "ricardo.garcia@masterconnoisseurs.com",
            ContactNumber = "+639177766554",
            DateOfBirth = new DateTime(1990, 06, 15),
            Address1 = "12 Maple St.",
            Address2 = null,
            AddressTownId = 4082,
            Address = "12 Maple St., Capatan, Tuguegarao City (Capital), Cagayan, Region II, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 5,
            AgentsId = 2,
            MCOrAgentId = "AGT1020",
            FirstName = "Nina",
            MiddleName = null,
            LastName = "Villar",
            Suffix = null,
            FullName = "Nina Villar",
            EmailAddress = "nina.villar@masterconnoisseurs.com",
            ContactNumber = "+639179912345",
            DateOfBirth = new DateTime(1995, 09, 22),
            Address1 = "34 Garden St.",
            Address2 = null,
            AddressTownId = 10258,
            Address = "34 Garden St., Congbalay-Legaspi, Kawit, Cavite, Region IV-A, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 6,
            AgentsId = 2,
            MCOrAgentId = "AGT1021",
            FirstName = "Alfred",
            MiddleName = "G.",
            LastName = "Torres",
            Suffix = "Sr.",
            FullName = "Alfred G. Torres Sr.",
            EmailAddress = "alfred.torres@masterconnoisseurs.com",
            ContactNumber = "+639174411223",
            DateOfBirth = new DateTime(1983, 03, 09),
            Address1 = "56 Lakeview Dr.",
            Address2 = null,
            AddressTownId = 10345,
            Address = "56 Lakeview Dr., Ibayo Silangan, Naic, Cavite, Region IV-A, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 7,
            AgentsId = 3,
            MCOrAgentId = "AGT1022",
            FirstName = "Bianca",
            MiddleName = null,
            LastName = "Delgado",
            Suffix = null,
            FullName = "Bianca Delgado",
            EmailAddress = "bianca.delgado@masterconnoisseurs.com",
            ContactNumber = "+639175533221",
            DateOfBirth = new DateTime(1991, 12, 12),
            Address1 = "89 Rose St.",
            Address2 = null,
            AddressTownId = 11209,
            Address = "89 Rose St., Macasipac, Santa Maria, Laguna, Region IV-A, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 8,
            AgentsId = 3,
            MCOrAgentId = "AGT1023",
            FirstName = "Jorge",
            MiddleName = "M.",
            LastName = "Ramos",
            Suffix = null,
            FullName = "Jorge M. Ramos",
            EmailAddress = "jorge.ramos@masterconnoisseurs.com",
            ContactNumber = "+639178833221",
            DateOfBirth = new DateTime(1987, 08, 19),
            Address1 = "22 Hill St.",
            Address2 = null,
            AddressTownId = 11844,
            Address = "22 Hill St., Vegaflor, Lopez, Quezon, Region IV-A, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 9,
            AgentsId = 3,
            MCOrAgentId = "AGT1024",
            FirstName = "Samantha",
            MiddleName = null,
            LastName = "Ortiz",
            Suffix = null,
            FullName = "Samantha Ortiz",
            EmailAddress = "samantha.ortiz@masterconnoisseurs.com",
            ContactNumber = "+639172244556",
            DateOfBirth = new DateTime(1993, 04, 23),
            Address1 = "101 Sunrise St.",
            Address2 = null,
            AddressTownId = 12750,
            Address = "101 Sunrise St., Sawi, Boac (Capital), Marinduque, Region IV-B, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 10,
            AgentsId = 4,
            MCOrAgentId = "AGT1025",
            FirstName = "Daniel",
            MiddleName = null,
            LastName = "Navarro",
            Suffix = null,
            FullName = "Daniel Navarro",
            EmailAddress = "daniel.navarro@masterconnoisseurs.com",
            ContactNumber = "+639176677889",
            DateOfBirth = new DateTime(1986, 07, 11),
            Address1 = "303 Elm St.",
            Address2 = null,
            AddressTownId = 13559,
            Address = "303 Elm St., Pasig, Balabac, Palawan, Region IV-B, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 11,
            AgentsId = 4,
            MCOrAgentId = "AGT1026",
            FirstName = "Vanessa",
            MiddleName = "T.",
            LastName = "Salazar",
            Suffix = null,
            FullName = "Vanessa T. Salazar",
            EmailAddress = "vanessa.salazar@masterconnoisseurs.com",
            ContactNumber = "+639179922334",
            DateOfBirth = new DateTime(1990, 02, 27),
            Address1 = "400 Pine St.",
            Address2 = null,
            AddressTownId = 14108,
            Address = "400 Pine St., Calunacon, San Andres, Romblon, Region IV-B, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 12,
            AgentsId = 4,
            MCOrAgentId = "AGT1027",
            FirstName = "Emilio",
            MiddleName = null,
            LastName = "Diaz",
            Suffix = null,
            FullName = "Emilio Diaz",
            EmailAddress = "emilio.diaz@masterconnoisseurs.com",
            ContactNumber = "+639178855443",
            DateOfBirth = new DateTime(1984, 03, 15),
            Address1 = "55 Cedar St.",
            Address2 = null,
            AddressTownId = 14502,
            Address = "55 Cedar St., Tambo, Libon, Albay, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 13,
            AgentsId = 5,
            MCOrAgentId = "AGT1028",
            FirstName = "Gloria",
            MiddleName = null,
            LastName = "Mendoza",
            Suffix = null,
            FullName = "Gloria Mendoza",
            EmailAddress = "gloria.mendoza@masterconnoisseurs.com",
            ContactNumber = "+639172266778",
            DateOfBirth = new DateTime(1992, 09, 09),
            Address1 = "22 Park Ave.",
            Address2 = null,
            AddressTownId = 14624,
            Address = "22 Park Ave., Bagumbayan, Oas, Albay, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 14,
            AgentsId = 5,
            MCOrAgentId = "AGT1029",
            FirstName = "Hector",
            MiddleName = "J.",
            LastName = "Reyes",
            Suffix = null,
            FullName = "Hector J. Reyes",
            EmailAddress = "hector.reyes@masterconnoisseurs.com",
            ContactNumber = "+639177711223",
            DateOfBirth = new DateTime(1987, 01, 05),
            Address1 = "88 Sunset Blvd.",
            Address2 = null,
            AddressTownId = 15838,
            Address = "88 Sunset Blvd., San Vicente Ogbon, Nabua, Camarines Sur, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 15,
            AgentsId = 5,
            MCOrAgentId = "AGT1030",
            FirstName = "Isabel",
            MiddleName = null,
            LastName = "Torres",
            Suffix = null,
            FullName = "Isabel Torres",
            EmailAddress = "isabel.torres@masterconnoisseurs.com",
            ContactNumber = "+639175599112",
            DateOfBirth = new DateTime(1994, 11, 14),
            Address1 = "10 Maple St.",
            Address2 = null,
            AddressTownId = 16453,
            Address = "10 Maple St., Burgos, Viga, Catanduanes, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
    ];
}