namespace MC.IMS.TESTS.MockData.Reference;

public static class Providers
{
    public static IEnumerable<API.Models.Result.Reference.Providers> ProvidersList() =>
    [
        new()
        {
            Id = 1,
            Name = "Metro Health Supplies",
            Description = "Supplier of medical and health-related equipment.",
            Code = "MHS01",
            ContactPerson = "Dr. Carl M. Reyes",
            EmailAddress = "contact@metrohealthsupplies.com",
            ContactNumber = "+639371234580",
            Address1 = "123 Health Blvd",
            Address2 = null,
            AddressTownId = 16542,
            Address = "123 Health Blvd, Amotag, Aroroy, Masbate, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 2,
            Name = "Bright Pharma Distributors",
            Description = "Distributor of pharmaceutical products across regions.",
            Code = "BPD02",
            ContactPerson = "Maria L. Santos",
            EmailAddress = "info@brightpharma.com",
            ContactNumber = "+639381234581",
            Address1 = "456 Pharma St.",
            Address2 = null,
            AddressTownId = 16739,
            Address = "456 Pharma St., Peñafrancia, Claveria, Masbate, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 3,
            Name = "Evergreen Medical Supplies",
            Description = "Providing eco-friendly medical consumables.",
            Code = "EMS03",
            ContactPerson = "Jose R. Delgado",
            EmailAddress = "support@evergreenmedsupplies.com",
            ContactNumber = "+639391234582",
            Address1 = "789 Evergreen Rd.",
            Address2 = null,
            AddressTownId = 16958,
            Address = "789 Evergreen Rd., Dangpanan, Placer, Masbate, Region V, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 4,
            Name = "CarePlus Diagnostics",
            Description = "Diagnostic equipment and lab services supplier.",
            Code = "CPD04",
            ContactPerson = "Anna G. Villanueva",
            EmailAddress = "contact@careplusdiagnostics.com",
            ContactNumber = "+639401234583",
            Address1 = "321 Care St.",
            Address2 = null,
            AddressTownId = 17763,
            Address = "321 Care St., Linabuan Norte, Kalibo (Capital), Aklan, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 5,
            Name = "Harmony Medical Distributors",
            Description = "Supplier of general and specialty medical products.",
            Code = "HMD05",
            ContactPerson = "Ricardo P. Garcia",
            EmailAddress = "info@harmonymedical.com",
            ContactNumber = "+639411234584",
            Address1 = "654 Harmony Ave.",
            Address2 = null,
            AddressTownId = 18624,
            Address = "654 Harmony Ave., Jambad, Dumarao, Capiz, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 6,
            Name = "Prime Medical Equipment",
            Description = "Supplier of advanced medical devices and equipment.",
            Code = "PME06",
            ContactPerson = "Liza M. Cruz",
            EmailAddress = "contact@primemedical.com",
            ContactNumber = "+639421234585",
            Address1 = "987 Prime St.",
            Address2 = null,
            AddressTownId = 19573,
            Address = "987 Prime St., Ermita, Dumangas, Iloilo, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 7,
            Name = "HealthPro Solutions",
            Description = "Distributor of health and wellness products.",
            Code = "HPS07",
            ContactPerson = "Miguel A. Santos",
            EmailAddress = "info@healthprosolutions.com",
            ContactNumber = "+639431234586",
            Address1 = "246 Health Rd.",
            Address2 = null,
            AddressTownId = 19844,
            Address = "246 Health Rd., San Nicolas, Iloilo City (Capital), Iloilo, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 8,
            Name = "Medico Pharma Distributors",
            Description = "Supplier of pharmaceutical and healthcare products.",
            Code = "MPD08",
            ContactPerson = "Elena V. Reyes",
            EmailAddress = "support@medicopharma.com",
            ContactNumber = "+639441234587",
            Address1 = "135 Medico Blvd.",
            Address2 = null,
            AddressTownId = 21303,
            Address = "135 Medico Blvd., La Granja, La Carlota City, Negros Occidental, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 9,
            Name = "WellCare Medical Supplies",
            Description = "Provider of medical and wellness supplies.",
            Code = "WMS09",
            ContactPerson = "Juan P. dela Cruz",
            EmailAddress = "contact@wellcaremedical.com",
            ContactNumber = "+639451234588",
            Address1 = "357 Wellness St.",
            Address2 = null,
            AddressTownId = 21378,
            Address = "357 Wellness St., Buenavista Rizal, Pontevedra, Negros Occidental, Region VI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 10,
            Name = "CareFirst Medical Distribution",
            Description = "Leading supplier of medical devices and consumables.",
            Code = "CFM10",
            ContactPerson = "Anna L. Morales",
            EmailAddress = "info@carefirstmedical.com",
            ContactNumber = "+639461234589",
            Address1 = "468 Carefirst Ave.",
            Address2 = null,
            AddressTownId = 21854,
            Address = "468 Carefirst Ave., Nueva Montana, Buenavista, Bohol, Region VII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 11,
            Name = "Global Health Supplies",
            Description = "International supplier of medical and health products.",
            Code = "GHS11",
            ContactPerson = "Maria R. Santos",
            EmailAddress = "contact@globalhealthsupplies.com",
            ContactNumber = "+639471234590",
            Address1 = "789 Global St.",
            Address2 = null,
            AddressTownId = 22952,
            Address = "789 Global St., Matun-og, Balamban, Cebu, Region VII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 12,
            Name = "MediSource Inc.",
            Description = "Distributor of pharmaceutical and medical equipment.",
            Code = "MSI12",
            ContactPerson = "Carlos D. Villanueva",
            EmailAddress = "info@medisource.com",
            ContactNumber = "+639481234591",
            Address1 = "123 Medi Lane",
            Address2 = null,
            AddressTownId = 23301,
            Address = "123 Medi Lane, Casay, Dalaguete, Cebu, Region VII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 13,
            Name = "HealthTech Solutions",
            Description = "Supplier of innovative healthcare technologies.",
            Code = "HTS13",
            ContactPerson = "Ana G. Fernandez",
            EmailAddress = "support@healthtechsolutions.com",
            ContactNumber = "+639491234592",
            Address1 = "456 Tech Park",
            Address2 = null,
            AddressTownId = 24081,
            Address = "456 Tech Park, Tangculogan, Bais City, Negros Oriental, Region VII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 14,
            Name = "VitalCare Distributors",
            Description = "Reliable supplier of vital care medical products.",
            Code = "VCD14",
            ContactPerson = "Jose M. Cruz",
            EmailAddress = "contact@vitalcaredist.com",
            ContactNumber = "+639501234593",
            Address1 = "321 Vital St.",
            Address2 = null,
            AddressTownId = 25013,
            Address = "321 Vital St., Barangay Poblacion 8, Lawaan, Eastern Samar, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 15,
            Name = "MediPlus Supplies",
            Description = "Distributor of medical consumables and equipment.",
            Code = "MPS15",
            ContactPerson = "Luisa T. Mendoza",
            EmailAddress = "info@mediplussupplies.com",
            ContactNumber = "+639511234594",
            Address1 = "654 Plus Ave.",
            Address2 = null,
            AddressTownId = 25239,
            Address = "654 Plus Ave., Tan-awan, San Policarpo, Eastern Samar, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 16,
            Name = "CareFirst Medical",
            Description = "Leading provider of healthcare equipment and supplies.",
            Code = "CFM16",
            ContactPerson = "Pedro L. Ramos",
            EmailAddress = "contact@carefirstmedical.com",
            ContactNumber = "+639521234595",
            Address1 = "789 Care St.",
            Address2 = null,
            AddressTownId = 26397,
            Address = "789 Care St., Barangay 25 (Pob.), Ormoc City, Leyte, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 17,
            Name = "PharmaLink Distributors",
            Description = "Supplier of pharmaceutical drugs and medical supplies.",
            Code = "PLD17",
            ContactPerson = "Sonia G. Aquino",
            EmailAddress = "info@pharmalink.com",
            ContactNumber = "+639531234596",
            Address1 = "123 Pharma Rd.",
            Address2 = null,
            AddressTownId = 28171,
            Address = "123 Pharma Rd., Cabunga-an, Santa Rita, Samar, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 18,
            Name = "MedEquip Solutions",
            Description = "Provider of advanced medical equipment and tools.",
            Code = "MES18",
            ContactPerson = "Ramon V. Diaz",
            EmailAddress = "support@medequipsolutions.com",
            ContactNumber = "+639541234597",
            Address1 = "456 Equip Blvd.",
            Address2 = null,
            AddressTownId = 28710,
            Address = "456 Equip Blvd., San Jose, Malitbog, Southern Leyte, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 19,
            Name = "Wellness Supplies Inc.",
            Description = "Distributor of wellness and healthcare products.",
            Code = "WSI19",
            ContactPerson = "Elena M. Cruz",
            EmailAddress = "contact@wellnesssupplies.com",
            ContactNumber = "+639551234598",
            Address1 = "789 Wellness St.",
            Address2 = null,
            AddressTownId = 28847,
            Address = "789 Wellness St., Looc, San Ricardo, Southern Leyte, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 20,
            Name = "HealthPrime Solutions",
            Description = "Supplier of premium medical and healthcare equipment.",
            Code = "HPS20",
            ContactPerson = "Daniel P. Garcia",
            EmailAddress = "info@healthprimesolutions.com",
            ContactNumber = "+639561234599",
            Address1 = "123 Prime Ave.",
            Address2 = null,
            AddressTownId = 28961,
            Address = "123 Prime Ave., Canila, Biliran, Biliran, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        }
    ];
}