namespace MC.IMS.TESTS.MockData.Reference;

public static class SalesManagers
{
    public static IEnumerable<API.Models.Result.Reference.SalesManagers> SalesManagersList() =>
    [
        new()
        {
            Id = 3,
            AgentsId = 1,
            MCOrAgentId = "AGT046",
            FirstName = "Angelica",
            MiddleName = "S",
            LastName = "Torres",
            Suffix = null,
            FullName = "Angelica S. Torres",
            EmailAddress = "angelica.torres@masterconnoisseurs.com",
            ContactNumber = "+639178123456",
            DateOfBirth = new DateTime(1991, 05, 18),
            Address1 = "45 Palm St.",
            Address2 = null,
            AddressTownId = 28983,
            Address = "45 Palm St., Binohangan, Caibiran, Biliran, Region VIII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 4,
            AgentsId = 1,
            MCOrAgentId = "AGT047",
            FirstName = "Jonathan",
            MiddleName = null,
            LastName = "Reyes",
            Suffix = "Jr.",
            FullName = "Jonathan Reyes Jr.",
            EmailAddress = "jonathan.reyes@masterconnoisseurs.com",
            ContactNumber = "+639175678901",
            DateOfBirth = new DateTime(1987, 08, 22),
            Address1 = "120 Oak St.",
            Address2 = "Blk 9 Lot 3",
            AddressTownId = 30177,
            Address =
                "120 Oak St., Blk 9 Lot 3, San Pedro (Pob.), Pagadian City (Capital), Zamboanga del Sur, Region IX, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 5,
            AgentsId = 1,
            MCOrAgentId = "AGT048",
            FirstName = "Beatrice",
            MiddleName = "M",
            LastName = "Delgado",
            Suffix = null,
            FullName = "Beatrice M. Delgado",
            EmailAddress = "beatrice.delgado@masterconnoisseurs.com",
            ContactNumber = "+639179876234",
            DateOfBirth = new DateTime(1990, 12, 05),
            Address1 = "33 Maple Ave.",
            Address2 = null,
            AddressTownId = 30298,
            Address = "33 Maple Ave., New Village (Pob.), Tambulig, Zamboanga del Sur, Region IX, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 6,
            AgentsId = 2,
            MCOrAgentId = "AGT049",
            FirstName = "Ernest",
            MiddleName = "L",
            LastName = "Castillo",
            Suffix = null,
            FullName = "Ernest L. Castillo",
            EmailAddress = "ernest.castillo@masterconnoisseurs.com",
            ContactNumber = "+639170987654",
            DateOfBirth = new DateTime(1982, 03, 15),
            Address1 = "78 Birch Rd.",
            Address2 = "Apt 201",
            AddressTownId = 31659,
            Address = "78 Birch Rd., Apt 201, Mamagum, Sultan Naga Dimaporo, Lanao del Norte, Region X, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 7,
            AgentsId = 2,
            MCOrAgentId = "AGT050",
            FirstName = "Jessica",
            MiddleName = null,
            LastName = "Flores",
            Suffix = null,
            FullName = "Jessica Flores",
            EmailAddress = "jessica.flores@masterconnoisseurs.com",
            ContactNumber = "+639171234890",
            DateOfBirth = new DateTime(1994, 07, 29),
            Address1 = "56 Cedar St.",
            Address2 = null,
            AddressTownId = 32311,
            Address = "56 Cedar St., Mohon, Panaon, Misamis Occidental, Region X, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 8,
            AgentsId = 2,
            MCOrAgentId = "AGT051",
            FirstName = "Roland",
            MiddleName = "A",
            LastName = "Navarro",
            Suffix = null,
            FullName = "Roland A. Navarro",
            EmailAddress = "roland.navarro@masterconnoisseurs.com",
            ContactNumber = "+639178901234",
            DateOfBirth = new DateTime(1986, 11, 10),
            Address1 = "94 Pine Ln.",
            Address2 = "Unit 7",
            AddressTownId = 32811,
            Address = "94 Pine Ln., Unit 7, Salicapawan, Kinoguitan, Misamis Oriental, Region X, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 9,
            AgentsId = 3,
            MCOrAgentId = "AGT052",
            FirstName = "Sophia",
            MiddleName = "G",
            LastName = "Morales",
            Suffix = null,
            FullName = "Sophia G. Morales",
            EmailAddress = "sophia.morales@masterconnoisseurs.com",
            ContactNumber = "+639172345109",
            DateOfBirth = new DateTime(1993, 04, 21),
            Address1 = "87 Elm Dr.",
            Address2 = null,
            AddressTownId = 33025,
            Address = "87 Elm Dr., Guadalupe, Carmen, Davao del Norte, Region XI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 10,
            AgentsId = 3,
            MCOrAgentId = "AGT053",
            FirstName = "Miguel",
            MiddleName = null,
            LastName = "Luna",
            Suffix = null,
            FullName = "Miguel Luna",
            EmailAddress = "miguel.luna@masterconnoisseurs.com",
            ContactNumber = "+639179876019",
            DateOfBirth = new DateTime(1980, 09, 07),
            Address1 = "15 Redwood St.",
            Address2 = null,
            AddressTownId = 33219,
            Address = "15 Redwood St., Pinamuno, San Isidro, Davao del Norte, Region XI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 11,
            AgentsId = 3,
            MCOrAgentId = "AGT054",
            FirstName = "Nina",
            MiddleName = "T",
            LastName = "Salvador",
            Suffix = "III",
            FullName = "Nina T. Salvador III",
            EmailAddress = "nina.salvador@masterconnoisseurs.com",
            ContactNumber = "+639173456210",
            DateOfBirth = new DateTime(1991, 01, 30),
            Address1 = "48 Spruce Blvd.",
            Address2 = "Suite 12",
            AddressTownId = 33764,
            Address = "48 Spruce Blvd., Suite 12, San Ignacio, Manay, Davao Oriental, Region XI, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 12,
            AgentsId = 4,
            MCOrAgentId = "AGT055",
            FirstName = "Jason",
            MiddleName = "B",
            LastName = "Dela Cruz",
            Suffix = null,
            FullName = "Jason B. Dela Cruz",
            EmailAddress = "jason.delacruz@masterconnoisseurs.com",
            ContactNumber = "+639170987321",
            DateOfBirth = new DateTime(1989, 06, 15),
            Address1 = "62 Cypress Rd.",
            Address2 = null,
            AddressTownId = 34370,
            Address = "62 Cypress Rd., Kabulacan, Matalam, Cotabato, Region XII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 13,
            AgentsId = 4,
            MCOrAgentId = "AGT056",
            FirstName = "Rhea",
            MiddleName = null,
            LastName = "Villar",
            Suffix = null,
            FullName = "Rhea Villar",
            EmailAddress = "rhea.villar@masterconnoisseurs.com",
            ContactNumber = "+639174321987",
            DateOfBirth = new DateTime(1996, 10, 22),
            Address1 = "110 Chestnut Ave.",
            Address2 = null,
            AddressTownId = 34843,
            Address = "110 Chestnut Ave., Lampitak, Tampakan, South Cotabato, Region XII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 14,
            AgentsId = 4,
            MCOrAgentId = "AGT057",
            FirstName = "Daniel",
            MiddleName = "M",
            LastName = "Mendoza",
            Suffix = null,
            FullName = "Daniel M. Mendoza",
            EmailAddress = "daniel.mendoza@masterconnoisseurs.com",
            ContactNumber = "+639178654321",
            DateOfBirth = new DateTime(1984, 02, 18),
            Address1 = "27 Fir St.",
            Address2 = "Apt 8C",
            AddressTownId = 35205,
            Address = "27 Fir St., Apt 8C, Glan Padidu, Glan, Sarangani, Region XII, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 15,
            AgentsId = 5,
            MCOrAgentId = "AGT058",
            FirstName = "Camille",
            MiddleName = "R",
            LastName = "Garcia",
            Suffix = null,
            FullName = "Camille R. Garcia",
            EmailAddress = "camille.garcia@masterconnoisseurs.com",
            ContactNumber = "+639171234098",
            DateOfBirth = new DateTime(1992, 03, 25),
            Address1 = "59 Willow Dr.",
            Address2 = null,
            AddressTownId = 35372,
            Address = "59 Willow Dr., Barangay 15, Manila City (Capital), Metro Manila, NCR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 16,
            AgentsId = 5,
            MCOrAgentId = "AGT059",
            FirstName = "Francis",
            MiddleName = null,
            LastName = "Salazar",
            Suffix = null,
            FullName = "Francis Salazar",
            EmailAddress = "francis.salazar@masterconnoisseurs.com",
            ContactNumber = "+639179876543",
            DateOfBirth = new DateTime(1988, 12, 14),
            Address1 = "101 Maple Ln.",
            Address2 = "Suite 2B",
            AddressTownId = 36602,
            Address = "101 Maple Ln., Suite 2B, Barangay 112, Caloocan City, Metro Manila, NCR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 17,
            AgentsId = 5,
            MCOrAgentId = "AGT060",
            FirstName = "Olivia",
            MiddleName = "L",
            LastName = "Castillo",
            Suffix = null,
            FullName = "Olivia L. Castillo",
            EmailAddress = "olivia.castillo@masterconnoisseurs.com",
            ContactNumber = "+639170987654",
            DateOfBirth = new DateTime(1990, 07, 09),
            Address1 = "85 Pine St.",
            Address2 = null,
            AddressTownId = 36872,
            Address = "85 Pine St., Barangay 44, Pasay City, Metro Manila, NCR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
    ];
}