namespace MC.IMS.TESTS.MockData.Reference;

public static class SelectionList
{
    public static IEnumerable<API.Models.Result.Reference.SelectionList> SelectionListItems() =>
    [
        new()
        {
            Id = 1,
            SelectionTypeId = 1,
            Name = "Drivers License",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 2,
            SelectionTypeId = 1,
            Name = "Passport",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 3,
            SelectionTypeId = 1,
            Name = "SSS ID",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 4,
            SelectionTypeId = 1,
            Name = "UMID",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 5,
            SelectionTypeId = 1,
            Name = "Voters ID",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 6,
            SelectionTypeId = 1,
            Name = "Philhealth ID",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 7,
            SelectionTypeId = 2,
            Name = "Spouse",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 8,
            SelectionTypeId = 2,
            Name = "Child",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 9,
            SelectionTypeId = 2,
            Name = "Parent",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 10,
            SelectionTypeId = 2,
            Name = "Sibling",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 11,
            SelectionTypeId = 2,
            Name = "Grandparent",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 12,
            SelectionTypeId = 2,
            Name = "Grandchild",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 13,
            SelectionTypeId = 2,
            Name = "Aunt/Uncle",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 14,
            SelectionTypeId = 2,
            Name = "Niece/Nephew",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 15,
            SelectionTypeId = 2,
            Name = "Cousin",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 16,
            SelectionTypeId = 2,
            Name = "Friend",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 17,
            SelectionTypeId = 2,
            Name = "Other",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 18,
            SelectionTypeId = 2,
            Name = "Partner",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 19,
            SelectionTypeId = 2,
            Name = "Guardian",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 20,
            SelectionTypeId = 2,
            Name = "Ward",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 21,
            SelectionTypeId = 2,
            Name = "Employer",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 22,
            SelectionTypeId = 2,
            Name = "Employee",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 23,
            SelectionTypeId = 3,
            Name = "New",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 24,
            SelectionTypeId = 3,
            Name = "Renewal",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 25,
            SelectionTypeId = 3,
            Name = "Cancellation",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 26,
            SelectionTypeId = 3,
            Name = "Additional",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 27,
            SelectionTypeId = 4,
            Name = "Cash",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 28,
            SelectionTypeId = 4,
            Name = "Credit Card",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 29,
            SelectionTypeId = 4,
            Name = "Debit Card",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 30,
            SelectionTypeId = 4,
            Name = "Bank Transfer",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 31,
            SelectionTypeId = 4,
            Name = "Mobile Payment",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 32,
            SelectionTypeId = 4,
            Name = "Online Payment Gateway",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 33,
            SelectionTypeId = 4,
            Name = "E-Wallet",
            Description = null,
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
    ];
}