namespace MC.IMS.TESTS.MockData.Reference;

public static class SubAgents
{
    public static IEnumerable<API.Models.Result.Reference.SubAgents> SubAgentsList() =>
    [
        new()
        {
            Id = 1,
            MCOrAgentId = "AGT1011",
            FirstName = "Monica",
            MiddleName = null,
            LastName = "Reyes",
            Suffix = null,
            FullName = "Monica Reyes",
            EmailAddress = "monica.reyes@masterconnoisseurs.com",
            ContactNumber = "+639171122334",
            DateOfBirth = new DateTime(1991, 07, 12),
            Address1 = "123 Greenfield St.",
            Address2 = null,
            AddressTownId = 37150,
            Address = "123 Greenfield St., Lub-lubba, Dolores, Abra, CAR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 2,
            MCOrAgentId = "AGT1012",
            FirstName = "Elijah",
            MiddleName = "M.",
            LastName = "Torres",
            Suffix = null,
            FullName = "Elijah M. Torres",
            EmailAddress = "elijah.torres@masterconnoisseurs.com",
            ContactNumber = "+639178899001",
            DateOfBirth = new DateTime(1985, 02, 20),
            Address1 = "45 Sunrise Blvd.",
            Address2 = null,
            AddressTownId = 37464,
            Address = "45 Sunrise Blvd., Teodora Alonzo, Baguio City, Benguet, CAR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 3,
            MCOrAgentId = "AGT1013",
            FirstName = "Angelica",
            MiddleName = null,
            LastName = "Velasco",
            Suffix = null,
            FullName = "Angelica Velasco",
            EmailAddress = "angelica.velasco@masterconnoisseurs.com",
            ContactNumber = "+639179988776",
            DateOfBirth = new DateTime(1994, 10, 30),
            Address1 = "Lot 7 Block 3",
            Address2 = "Camella Homes",
            AddressTownId = 38049,
            Address = "Lot 7 Block 3, Camella Homes, Buringal, Paracelis, Mountain Province, CAR, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 4,
            MCOrAgentId = "AGT1014",
            FirstName = "Ramon",
            MiddleName = "L.",
            LastName = "Castillo",
            Suffix = "Jr.",
            FullName = "Ramon L. Castillo Jr.",
            EmailAddress = "ramon.castillo@masterconnoisseurs.com",
            ContactNumber = "+639176655443",
            DateOfBirth = new DateTime(1979, 12, 05),
            Address1 = "85 Oakwood Ave.",
            Address2 = null,
            AddressTownId = 38703,
            Address = "85 Oakwood Ave., Pangadapun, Ganassi, Lanao del Sur, ARMM, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
        new()
        {
            Id = 5,
            MCOrAgentId = "AGT1015",
            FirstName = "Leah",
            MiddleName = null,
            LastName = "Marquez",
            Suffix = null,
            FullName = "Leah Marquez",
            EmailAddress = "leah.marquez@masterconnoisseurs.com",
            ContactNumber = "+639172233445",
            DateOfBirth = new DateTime(1990, 09, 18),
            Address1 = "Unit 15, Blue Ridge",
            Address2 = "Green Meadows",
            AddressTownId = 39078,
            Address = "Unit 15, Blue Ridge, Green Meadows, Diampaca, Pagayawan, Lanao del Sur, ARMM, Philippines",
            IsActive = true,
            CreatedBy = null,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = null,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
        },
    ];
}