namespace MC.IMS.TESTS.MockData.Transaction;

public static class GroupPolicy
{
    public static IEnumerable<API.Models.Result.Transaction.GroupPolicy> GroupPolicyList() =>
    [
        new()
        {
            Id = 8,
            ReferenceNumber = "GPB000000001",
            CocNumber = "000000000001",
            PartnersId = 5,
            PlatformsId = 27,
            IssueStatus = true,
            PolicyBookingStatusId = 3,
            CocStatusId = 1,
            PaymentStatusId = 1,
            ClaimsStatusId = 3,
            AgentsId = 1,
            SubAgentsId = 2,
            ApproversId = 3,
            PromoManagersId = null,
            SalesManagersId = null,
            PromoOfficersId = null,
            ProductsId = 1,
            ProvidersId = 11,
            DistributionChannelId = 4,
            PaymentOptionId = 27,
            AccountTypeId = 23,
            BranchCode = "35265",
            BranchName = "885669",
            ProviderPolicyNo = "PPN-IMS3-001",
            EndorsementNo = "EN-IMS3-001",
            TerminationDate = new DateTime(2026, 06, 07),
            EffectiveDate = new DateTime(2025, 06, 07),
            IssueDate = new DateTime(2025, 06, 07),
            Remarks = "Remarks",
            TotalPremium = 645.17m,
            TotalCoverage = 56000.00m,
            TotalPaid = 645.17m,
            CreatedBy = 500329,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = 500329,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),

            //Premiums
            BasicPremium = 10,
            BasicPremiumCommission = 20,
            MCMarkup = 30,
            PartnerMarkup = 40,
            Discount = 130,
            Taxes = 50,
            DST = 60,
            VAT = 70,
            LGT = 80,
            PT = 90,
            FST = 100,
            NotarialFee = 110,
            Others = 120,
            PremiumsRemarks = "Premium Remarks"
        },
        new()
        {
            Id = 9,
            ReferenceNumber = "GPB000000002",
            CocNumber = "000000000002",
            PartnersId = 5,
            PlatformsId = 27,
            IssueStatus = true,
            PolicyBookingStatusId = 3,
            CocStatusId = 1,
            PaymentStatusId = 1,
            ClaimsStatusId = 3,
            AgentsId = 1,
            SubAgentsId = null,
            ApproversId = 3,
            PromoManagersId = 1,
            SalesManagersId = 3,
            PromoOfficersId = 2,
            ProductsId = 1,
            ProvidersId = 11,
            DistributionChannelId = 7,
            PaymentOptionId = 27,
            AccountTypeId = 23,
            BranchCode = null,
            BranchName = null,
            ProviderPolicyNo = "PPN-IMS3-001",
            EndorsementNo = "EN-IMS3-002",
            TerminationDate = new DateTime(2026, 06, 07),
            EffectiveDate = new DateTime(2025, 06, 07),
            IssueDate = new DateTime(2025, 06, 07),
            Remarks = "Remarks",
            TotalPremium = 645.17m,
            TotalCoverage = 56000.00m,
            TotalPaid = 645.17m,
            CreatedBy = 500329,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = 500329,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),

            //Premiums
            BasicPremium = 10,
            BasicPremiumCommission = 20,
            MCMarkup = 30,
            PartnerMarkup = 40,
            Discount = 130,
            Taxes = 50,
            DST = 60,
            VAT = 70,
            LGT = 80,
            PT = 90,
            FST = 100,
            NotarialFee = 110,
            Others = 120,
            PremiumsRemarks = "Premium Remarks"
        },
        new()
        {
            Id = 10,
            ReferenceNumber = "GPB000000003",
            CocNumber = "000000000003",
            PartnersId = 5,
            PlatformsId = 27,
            IssueStatus = true,
            PolicyBookingStatusId = 3,
            CocStatusId = 1,
            PaymentStatusId = 1,
            ClaimsStatusId = 3,
            AgentsId = 1,
            SubAgentsId = 2,
            ApproversId = 3,
            PromoManagersId = null,
            SalesManagersId = null,
            PromoOfficersId = null,
            ProductsId = 1,
            ProvidersId = 11,
            DistributionChannelId = 3,
            PaymentOptionId = 27,
            AccountTypeId = 23,
            BranchCode = null,
            BranchName = null,
            ProviderPolicyNo = "PPN-IMS3-001",
            EndorsementNo = "EN-IMS3-003",
            TerminationDate = new DateTime(2026, 06, 07),
            EffectiveDate = new DateTime(2025, 06, 07),
            IssueDate = new DateTime(2025, 06, 07),
            Remarks = "Remarks",
            TotalPremium = 645.17m,
            TotalCoverage = 56000.00m,
            TotalPaid = 645.17m,
            CreatedBy = 500329,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = 500329,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),

            //Premiums
            BasicPremium = 10,
            BasicPremiumCommission = 20,
            MCMarkup = 30,
            PartnerMarkup = 40,
            Discount = 130,
            Taxes = 50,
            DST = 60,
            VAT = 70,
            LGT = 80,
            PT = 90,
            FST = 100,
            NotarialFee = 110,
            Others = 120,
            PremiumsRemarks = "Premium Remarks"
        }
    ];
}