namespace MC.IMS.TESTS.MockData.Transaction.View;

public static class PolicyBeneficiaryView
{
    public static IEnumerable<API.Models.Result.Transaction.PolicyBeneficiaryView> PolicyBeneficiaryViewList() =>
    [
        new()
        {
            Id = 10,
            PolicyId = 1,
            ReferenceNumber = "IPB000000001",
            CocNumber = "000000000004",
            PolicyType = "Individual",
            FirstName = "Maria",
            MiddleName = "C",
            LastName = "Santos",
            Suffix = null,
            FullName = "Maria C. Santos",
            EmailAddress = "maria.santos@email.com",
            ContactNumber = "+639171234567",
            DateOfBirth = new DateTime(1985, 05, 15),
            RelationshipTitle = "Spouse",
            PolicyTypeId = 1,
            Relationship = 7,
            CreatedBy = 500329,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = 500329,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0)
        },
        new()
        {
            Id = 11,
            PolicyId = 2,
            ReferenceNumber = "IPB000000002",
            CocNumber = "000000000005",
            PolicyType = "Individual",
            FirstName = "John",
            MiddleName = null,
            LastName = "Lim",
            Suffix = "Jr.",
            FullName = "John Lim Jr.",
            EmailAddress = "john.lim@email.com",
            ContactNumber = "+639189876543",
            DateOfBirth = new DateTime(1990, 11, 22),
            RelationshipTitle = "Sibling",
            PolicyTypeId = 1,
            Relationship = 10,
            CreatedBy = 500329,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = 500329,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0)
        },
        new()
        {
            Id = 12,
            PolicyId = 1,
            ReferenceNumber = "PPB000000001",
            CocNumber = "000000000006",
            PolicyType = "Partner",
            FirstName = "Sophia",
            MiddleName = "R",
            LastName = "Gonzales",
            Suffix = null,
            FullName = "Sophia R. Gonzales",
            EmailAddress = "sophia.g@email.com",
            ContactNumber = "+639201122334",
            DateOfBirth = new DateTime(1978, 01, 30),
            RelationshipTitle = "Aunt/Uncle",
            PolicyTypeId = 2,
            Relationship = 13,
            CreatedBy = 500329,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = 500329,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0)
        },
        new()
        {
            Id = 13,
            PolicyId = 2,
            ReferenceNumber = "PPB000000002",
            CocNumber = "000000000007",
            PolicyType = "Partner",
            FirstName = "David",
            MiddleName = "M",
            LastName = "Reyes",
            Suffix = "III",
            FullName = "David M. Reyes III",
            EmailAddress = "david.r@email.com",
            ContactNumber = "+639165566778",
            DateOfBirth = new DateTime(2005, 08, 01),
            RelationshipTitle = "Friend",
            PolicyTypeId = 2,
            Relationship = 16,
            CreatedBy = 500329,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = 500329,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0)
        },
        new()
        {
            Id = 14,
            PolicyId = 8,
            ReferenceNumber = "GPB000000001",
            CocNumber = "000000000001",
            PolicyType = "Group",
            FirstName = "Anna",
            MiddleName = null,
            LastName = "Cruz",
            Suffix = null,
            FullName = "Anna Cruz",
            EmailAddress = "anna.c@email.com",
            ContactNumber = "+639223344556",
            DateOfBirth = new DateTime(1962, 03, 10),
            RelationshipTitle = "Partner",
            PolicyTypeId = 3,
            Relationship = 18,
            CreatedBy = 500329,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = 500329,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0)
        },
        new()
        {
            Id = 15,
            PolicyId = 10,
            ReferenceNumber = "GPB000000003",
            CocNumber = "000000000003",
            PolicyType = "Group",
            FirstName = "Michael",
            MiddleName = "J",
            LastName = "Tan",
            Suffix = null,
            FullName = "Michael J. Tan",
            EmailAddress = "michael.t@email.com",
            ContactNumber = "+639190099887",
            DateOfBirth = new DateTime(1995, 09, 28),
            RelationshipTitle = "Ward",
            PolicyTypeId = 3,
            Relationship = 20,
            CreatedBy = 500329,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = 500329,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0)
        },
        new()
        {
            Id = 16,
            PolicyId = 9,
            ReferenceNumber = "GPB000000002",
            CocNumber = "000000000002",
            PolicyType = "Group",
            FirstName = "Ella",
            MiddleName = "P",
            LastName = "Ramos",
            Suffix = null,
            FullName = "Ella P. Ramos",
            EmailAddress = "ella.ramos@email.com",
            ContactNumber = "+639151239876",
            DateOfBirth = new DateTime(2000, 07, 25),
            RelationshipTitle = "Grandchild",
            PolicyTypeId = 3,
            Relationship = 12,
            CreatedBy = 500329,
            CreatedDateTime = new DateTime(2025, 06, 02, 0, 0, 0),
            ModifiedBy = 500329,
            ModifiedDateTime = new DateTime(2025, 06, 02, 0, 0, 0)
        }
    ];
}