namespace MC.IMS.TESTS.MockData.Dbo;

public static class TotalBookingPerStatus
{
    public static IEnumerable<API.Models.Result.Dbo.TotalBookingPerStatus> TotalBookingPerStatusList() =>
    [
        new()
        {
            ActivityDate = new DateTime(2025, 05, 20),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 21),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 22),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 23),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 24),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 25),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 26),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 27),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 28),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 29),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 30),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 05, 31),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 01),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 02),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 03),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 04),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 05),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 06),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 07),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 08),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 09),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 10),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 11),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 12),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 13),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 14),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 15),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 16),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 17),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
        new()
        {
            ActivityDate = new DateTime(2025, 06, 18),
            Approved = 0,
            Disapproved = 0,
            Pending = 0,
            Declined = 0,
            Quoted = 0,
            Draft = 0,
            AutoApproved = 0,
            TotalCount = 0,
        },
    ];
}